<?php

return array (
  0 => 
  array (
    'index' => 1003,
    'id' => 'about-2',
    'elementId' => 'about-3',
    'type' => 'section-available',
    'name' => 'About',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-about-2.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/about-2.png?v=1551109271',
    'description' => 'About',
    'category' => 'about',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canRevertColumnsOnMobile:true,contentAligns:[\'.content-col\'],sectionArea:{areaTitle:window.CP_Customizer.translateCompanionString("Content Column Options"),init:function($container){var contentbgcolor=CP_Customizer.createControl.color(this.getPrefixed(\'contentbgcolor\'),$container,{value:\'#ffffff\',label:window.CP_Customizer.translateCompanionString(\'Content Column Color\')});this.addToControlsList(contentbgcolor)},update:function(data){var dataId=\'[data-id=\'+data.section.attr(\'data-id\')+\'] \',selector=\'.content-col\',item=data.section.find(selector).eq(0),styleSelector=dataId+selector,currentColor=CP_Customizer.contentStyle.getNodeProp(item,styleSelector,null,\'background-color\');this.getControl(\'contentbgcolor\').attachWithSetter(currentColor,function(value){CP_Customizer.contentStyle.setProp(styleSelector,null,\'background-color\',value)})}}}',
  ),
  1 => 
  array (
    'index' => 1004,
    'id' => 'about-2-materialis',
    'elementId' => 'about-4',
    'type' => 'section-available',
    'name' => 'About',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-about-2-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/about-2-materialis.png?v=1551109271',
    'description' => 'About',
    'category' => 'about',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canRevertColumnsOnMobile:true,contentAligns:[\'.content-col\'],sectionArea:{areaTitle:window.CP_Customizer.translateCompanionString("Content Column Options"),init:function($container){var contentbgcolor=CP_Customizer.createControl.color(this.getPrefixed(\'contentbgcolor\'),$container,{value:\'#ffffff\',label:window.CP_Customizer.translateCompanionString(\'Content Column Color\')});this.addToControlsList(contentbgcolor);var contentbgimage=CP_Customizer.createControl.image(this.getPrefixed(\'contentbgimage\'),$container,{value:\'\',label:window.CP_Customizer.translateCompanionString(\'Content Background Image\')});this.addToControlsList(contentbgimage)},update:function(data){var dataId=\'[data-id=\'+data.section.attr(\'data-id\')+\'] \',selector=\'.div-content\',item=data.section.find(selector).eq(0),styleSelector=dataId+selector,currentColor=CP_Customizer.contentStyle.getNodeProp(item,styleSelector,null,\'background-color\');this.getControl(\'contentbgcolor\').attachWithSetter(currentColor,function(value){CP_Customizer.contentStyle.setProp(styleSelector,null,\'background-color\',value)});var selectorImage=".left-img",styleSelectorImage=dataId+selectorImage,itemImage=data.section.find(selectorImage).eq(0),currentImage=CP_Customizer.contentStyle.getNodeProp(itemImage,styleSelectorImage,null,\'background-image\');currentImage=CP_Customizer.utils.normalizeBackgroundImageValue(currentImage);this.getControl(\'contentbgimage\').attachWithSetter(currentImage,function(value){valueimage="url("+value+")";CP_Customizer.contentStyle.setProp(styleSelectorImage,null,\'background-image\',valueimage)})}}}',
  ),
  2 => 
  array (
    'index' => 1005,
    'id' => 'about-3',
    'elementId' => 'about-5',
    'type' => 'section-available',
    'name' => 'About',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-about-3.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/about-3.png?v=1551109271',
    'description' => 'About',
    'category' => 'about',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={contentAligns:[\'[data-type="column"]\'],sectionArea:{areaTitle:window.CP_Customizer.translateCompanionString("Section Options"),init:function($container){var contentbgcolor=CP_Customizer.createControl.color(this.getPrefixed(\'content-bg-color\'),$container,{value:\'#ffffff\',label:window.CP_Customizer.translateCompanionString(\'Content Column Bg. Color\')});this.addToControlsList(contentbgcolor)},update:function(data){var dataId=\'[data-id=\'+data.section.attr(\'data-id\')+\'] \',selector=\'.content-col\',item=data.section.find(selector).eq(0),styleSelector=dataId+selector,currentColor=CP_Customizer.contentStyle.getNodeProp(item,styleSelector,null,\'background-color\');this.getControl(\'content-bg-color\').attachWithSetter(currentColor,function(value){CP_Customizer.contentStyle.setProp(styleSelector,null,\'background-color\',value)})}}}',
  ),
  3 => 
  array (
    'index' => 1007,
    'id' => 'about-5',
    'elementId' => 'about-7',
    'type' => 'section-available',
    'name' => 'About',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-about-5.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/about-5.png?v=1551109271',
    'description' => 'About',
    'category' => 'about',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={contentAligns:[\'[data-type="column"]\'],sectionArea:{areaTitle:window.CP_Customizer.translateCompanionString("Section Options"),init:function($container){var contentbgcolor=CP_Customizer.createControl.color(this.getPrefixed(\'contentbgcolor\'),$container,{value:\'#ffffff\',label:window.CP_Customizer.translateCompanionString(\'Border Color\')});this.addToControlsList(contentbgcolor)},update:function(data){var dataId=\'[data-id=\'+data.section.attr(\'data-id\')+\'] \',selector=\'.center-overlay\',item=data.section.find(selector).eq(0),styleSelector=dataId+selector,currentColor=CP_Customizer.contentStyle.getNodeProp(item,styleSelector,null,\'border-color\');this.getControl(\'contentbgcolor\').attachWithSetter(currentColor,function(value){CP_Customizer.contentStyle.setProp(styleSelector,null,\'border-color\',value)})}}}',
  ),
  4 => 
  array (
    'index' => 1008,
    'id' => 'about-5-materialis',
    'elementId' => 'about-8',
    'type' => 'section-available',
    'name' => 'About',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-about-5-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/about-5-materialis.png?v=1551109271',
    'description' => 'About',
    'category' => 'about',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canRevertColumnsOnMobile:true,contentAligns:[\'[data-type="column"]\'],sectionArea:{areaTitle:window.CP_Customizer.translateCompanionString("Content Column Options"),init:function($container){var contentbgcolor=CP_Customizer.createControl.color(this.getPrefixed(\'contentbgcolor\'),$container,{value:\'#ffffff\',label:window.CP_Customizer.translateCompanionString(\'Content Column Overlay\')});this.addToControlsList(contentbgcolor);var contentbgimage=CP_Customizer.createControl.image(this.getPrefixed(\'contentbgimage\'),$container,{value:\'url("portrait-photography-657116.png")\',label:window.CP_Customizer.translateCompanionString(\'Content Background Image\')});this.addToControlsList(contentbgimage)},update:function(data){var dataId=\'[data-id=\'+data.section.attr(\'data-id\')+\'] \',selector=\'.content-overlay\',item=data.section.find(selector).eq(0),styleSelector=dataId+selector,currentColor=CP_Customizer.contentStyle.getNodeProp(item,styleSelector,\':after\',\'background-color\');this.getControl(\'contentbgcolor\').attachWithSetter(currentColor,function(value){CP_Customizer.contentStyle.setProp(styleSelector,\':after\',\'background-color\',value)});var styleSelectorImage=dataId+selector,currentImage=CP_Customizer.contentStyle.getNodeProp(item,styleSelectorImage,\':before\',\'background-image\');currentImage=CP_Customizer.utils.normalizeBackgroundImageValue(currentImage);this.getControl(\'contentbgimage\').attachWithSetter(currentImage,function(value){valueimage="url("+value+")";CP_Customizer.contentStyle.setProp(styleSelectorImage,\':before\',\'background-image\',valueimage)})}}}',
  ),
  5 => 
  array (
    'index' => 1009,
    'id' => 'about-6',
    'elementId' => 'about-9',
    'type' => 'section-available',
    'name' => 'About',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-about-6.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/about-6.png?v=1551109271',
    'description' => 'About',
    'category' => 'about',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={contentAligns:[\'[data-type="column"]\'],sectionArea:{areaTitle:window.CP_Customizer.translateCompanionString("Section Options"),init:function($container){var contentbgcolor=CP_Customizer.createControl.color(this.getPrefixed(\'contentbgcolor\'),$container,{value:\'#ffffff\',label:window.CP_Customizer.translateCompanionString(\'Border Color\')});this.addToControlsList(contentbgcolor)},update:function(data){var dataId=\'[data-id=\'+data.section.attr(\'data-id\')+\'] \',selector=\'.offset-double-border-overlay .border-1\',item=data.section.find(selector).eq(0),styleSelector=dataId+selector,currentColor=CP_Customizer.contentStyle.getNodeProp(item,styleSelector,null,\'border-color\');this.getControl(\'contentbgcolor\').attachWithSetter(currentColor,function(value){CP_Customizer.contentStyle.setProp(styleSelector,null,\'border-color\',value)})}}}',
  ),
  6 => 
  array (
    'index' => 1010,
    'id' => 'about-7',
    'elementId' => 'about-10',
    'type' => 'section-available',
    'name' => 'About',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-about-7.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/about-7.png?v=1551109271',
    'description' => 'About',
    'category' => 'about',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={contentAligns:[\'[data-type="column"]\'],sectionArea:{areaTitle:window.CP_Customizer.translateCompanionString("Section Options"),init:function($container){var contentbgcolor=CP_Customizer.createControl.color(this.getPrefixed(\'contentbgcolor\'),$container,{value:\'#ffffff\',label:window.CP_Customizer.translateCompanionString(\'Border Color\')});this.addToControlsList(contentbgcolor)},update:function(data){var dataId=\'[data-id=\'+data.section.attr(\'data-id\')+\'] \',selector=\'.center-overlay\',item=data.section.find(selector).eq(0),styleSelector=dataId+selector,currentColor=CP_Customizer.contentStyle.getNodeProp(item,styleSelector,null,\'border-color\');this.getControl(\'contentbgcolor\').attachWithSetter(currentColor,function(value){CP_Customizer.contentStyle.setProp(styleSelector,null,\'border-color\',value)})}}}',
  ),
  7 => 
  array (
    'index' => 1011,
    'id' => 'about-8',
    'elementId' => 'about-11',
    'type' => 'section-available',
    'name' => 'About',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-about-8.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/about-8.png?v=1551109271',
    'description' => 'About',
    'category' => 'about',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={contentAligns:[\'[data-type="column"]\'],sectionArea:{areaTitle:window.CP_Customizer.translateCompanionString("Section Options"),init:function($container){var contentbgcolor=CP_Customizer.createControl.color(this.getPrefixed(\'contentbgcolor\'),$container,{value:\'#ffffff\',label:window.CP_Customizer.translateCompanionString(\'Border Color\')});this.addToControlsList(contentbgcolor)},update:function(data){var dataId=\'[data-id=\'+data.section.attr(\'data-id\')+\'] \',selector=\'.center-overlay\',item=data.section.find(selector).eq(0),styleSelector=dataId+selector,currentColor=CP_Customizer.contentStyle.getNodeProp(item,styleSelector,null,\'border-color\');this.getControl(\'contentbgcolor\').attachWithSetter(currentColor,function(value){CP_Customizer.contentStyle.setProp(styleSelector,null,\'border-color\',value)})}}}',
  ),
  8 => 
  array (
    'index' => 1012,
    'id' => 'about-8-materialis',
    'elementId' => 'about-12',
    'type' => 'section-available',
    'name' => 'About',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-about-8-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/about-8-materialis.png?v=1551109271',
    'description' => 'About',
    'category' => 'about',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={contentAligns:[\'.vertical-align-content\']}',
  ),
  9 => 
  array (
    'index' => 1014,
    'id' => 'about-image-text',
    'elementId' => 'about-14',
    'type' => 'section-available',
    'name' => 'About',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-about-image-text.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/about-image-text.png?v=1551109271',
    'description' => 'About',
    'category' => 'about',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canRevertColumnsOnMobile:true,contentAligns:[\'[data-type="column"]\'],sectionArea:{areaTitle:window.CP_Customizer.translateCompanionString("Section Options"),init:function($container){var contentbgcolor=CP_Customizer.createControl.color(this.getPrefixed(\'contentbgcolor\'),$container,{value:\'#ffffff\',label:window.CP_Customizer.translateCompanionString(\'Content Column Color\')});this.addToControlsList(contentbgcolor)},update:function(data){var dataId=\'[data-id=\'+data.section.attr(\'data-id\')+\'] \',selector=\'.content-col\',item=data.section.find(selector).eq(0),styleSelector=dataId+selector,currentColor=CP_Customizer.contentStyle.getNodeProp(item,styleSelector,null,\'background-color\');this.getControl(\'contentbgcolor\').attachWithSetter(currentColor,function(value){CP_Customizer.contentStyle.setProp(styleSelector,null,\'background-color\',value)})}}}',
  ),
  10 => 
  array (
    'index' => 1016,
    'id' => 'about-text-image',
    'elementId' => 'about-16',
    'type' => 'section-available',
    'name' => 'About',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-about-text-image.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/about-text-image.png?v=1551109271',
    'description' => 'About',
    'category' => 'about',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={contentAligns:[\'[data-type="column"]\'],sectionArea:{areaTitle:window.CP_Customizer.translateCompanionString("Section Options"),init:function($container){var contentbgcolor=CP_Customizer.createControl.color(this.getPrefixed(\'contentbgcolor\'),$container,{value:\'#ffffff\',label:window.CP_Customizer.translateCompanionString(\'Content Column Color\')});this.addToControlsList(contentbgcolor)},update:function(data){var dataId=\'[data-id=\'+data.section.attr(\'data-id\')+\'] \',selector=\'.content-col\',item=data.section.find(selector).eq(0),styleSelector=dataId+selector,currentColor=CP_Customizer.contentStyle.getNodeProp(item,styleSelector,null,\'background-color\');this.getControl(\'contentbgcolor\').attachWithSetter(currentColor,function(value){CP_Customizer.contentStyle.setProp(styleSelector,null,\'background-color\',value)})}}}',
  ),
  11 => 
  array (
    'index' => 1017,
    'id' => 'clients-1',
    'elementId' => 'clients-1',
    'type' => 'section-available',
    'name' => 'Clients',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-clients-1.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/clients-1.png?v=1551109271',
    'description' => 'Clients',
    'category' => 'clients',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canAlignRowItemsContent:false}',
  ),
  12 => 
  array (
    'index' => 1020,
    'id' => 'clients-3',
    'elementId' => 'clients-4',
    'type' => 'section-available',
    'name' => 'Clients',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-clients-3.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/clients-3.png?v=1551109271',
    'description' => 'Clients',
    'category' => 'clients',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canAlignRowItemsContent:false}',
  ),
  13 => 
  array (
    'index' => 1021,
    'id' => 'clients-3-materialis',
    'elementId' => 'clients-5',
    'type' => 'section-available',
    'name' => 'Clients',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-clients-3-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/clients-3-materialis.png?v=1551109271',
    'description' => 'Clients',
    'category' => 'clients',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canAlignRowItemsContent:false,}',
  ),
  14 => 
  array (
    'index' => 1022,
    'id' => 'clients-4',
    'elementId' => 'clients-6',
    'type' => 'section-available',
    'name' => 'Clients',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-clients-4.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/clients-4.png?v=1551109271',
    'description' => 'Clients',
    'category' => 'clients',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canAlignRowItemsContent:false}',
  ),
  15 => 
  array (
    'index' => 1023,
    'id' => 'clients-4-materialis',
    'elementId' => 'clients-7',
    'type' => 'section-available',
    'name' => 'Clients',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-clients-4-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/clients-4-materialis.png?v=1551109271',
    'description' => 'Clients',
    'category' => 'clients',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canAlignRowItemsContent:false}',
  ),
  16 => 
  array (
    'index' => 1025,
    'id' => 'contact-1-materialis',
    'elementId' => 'contact-2',
    'type' => 'section-available',
    'name' => 'Contact',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-contact-1-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/contact-1-materialis.png?v=1551109271',
    'description' => 'Contact',
    'category' => 'contact',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={sectionArea:{areaTitle:window.CP_Customizer.translateCompanionString("Left Section Background"),init:function($container){var contentbgimage=CP_Customizer.createControl.image(this.getPrefixed(\'contentbgimage\'),$container,{value:\'url("contact-map_preview.png")\',label:window.CP_Customizer.translateCompanionString(\'Background Image\')});this.addToControlsList(contentbgimage)},update:function(data){var dataId=\'[data-id=\'+data.section.attr(\'data-id\')+\'] \',item=data.section.find(selector).eq(0);var selectorImage=".map-container",styleSelectorImage=dataId+selectorImage,itemImage=data.section.find(selectorImage).eq(0),currentImage=CP_Customizer.contentStyle.getNodeProp(itemImage,styleSelectorImage,null,\'background-image\');currentImage=CP_Customizer.utils.normalizeBackgroundImageValue(currentImage);this.getControl(\'contentbgimage\').attachWithSetter(currentImage,function(value){valueimage="url("+value+")";CP_Customizer.contentStyle.setProp(styleSelectorImage,null,\'background-image\',valueimage)})}}}',
  ),
  17 => 
  array (
    'index' => 1026,
    'id' => 'contact-2-materialis',
    'elementId' => 'contact-3',
    'type' => 'section-available',
    'name' => 'Contact',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-contact-2-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/contact-2-materialis.png?v=1551109271',
    'description' => 'Contact',
    'category' => 'contact',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  18 => 
  array (
    'index' => 1027,
    'id' => 'contact-3',
    'elementId' => 'contact-4',
    'type' => 'section-available',
    'name' => 'Contact',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-contact-3.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/contact-3.png?v=1551109271',
    'description' => 'Contact',
    'category' => 'contact',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  19 => 
  array (
    'index' => 1028,
    'id' => 'contact-3-materialis',
    'elementId' => 'contact-5',
    'type' => 'section-available',
    'name' => 'Contact',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-contact-3-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/contact-3-materialis.png?v=1551109271',
    'description' => 'Contact',
    'category' => 'contact',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={sectionArea:{areaTitle:window.CP_Customizer.translateCompanionString("Left Section Background"),init:function($container){var contentbgimage=CP_Customizer.createControl.image(this.getPrefixed(\'contentbgimage\'),$container,{value:\'url("contact-map_preview.png")\',label:window.CP_Customizer.translateCompanionString(\'Background Image\')});this.addToControlsList(contentbgimage)},update:function(data){var dataId=\'[data-id=\'+data.section.attr(\'data-id\')+\'] \',item=data.section.find(selector).eq(0);var selectorImage=".map-container",styleSelectorImage=dataId+selectorImage,itemImage=data.section.find(selectorImage).eq(0),currentImage=CP_Customizer.contentStyle.getNodeProp(itemImage,styleSelectorImage,null,\'background-image\');currentImage=CP_Customizer.utils.normalizeBackgroundImageValue(currentImage);this.getControl(\'contentbgimage\').attachWithSetter(currentImage,function(value){valueimage="url("+value+")";CP_Customizer.contentStyle.setProp(styleSelectorImage,null,\'background-image\',valueimage)})}}}',
  ),
  20 => 
  array (
    'index' => 1029,
    'id' => 'contact-4',
    'elementId' => 'contact-6',
    'type' => 'section-available',
    'name' => 'Contact',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-contact-4.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/contact-4.png?v=1551109271',
    'description' => 'Contact',
    'category' => 'contact',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  21 => 
  array (
    'index' => 1030,
    'id' => 'contact-5',
    'elementId' => 'contact-7',
    'type' => 'section-available',
    'name' => 'Contact',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-contact-5.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/contact-5.png?v=1551109271',
    'description' => 'Contact',
    'category' => 'contact',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={sectionArea:{areaTitle:window.CP_Customizer.translateCompanionString("Left Section Background"),init:function($container){var contentbgimage=CP_Customizer.createControl.image(this.getPrefixed(\'contentbgimage\'),$container,{value:\'url("contact-map_preview.png")\',label:window.CP_Customizer.translateCompanionString(\'Background Image\')});this.addToControlsList(contentbgimage)},update:function(data){var dataId=\'[data-id=\'+data.section.attr(\'data-id\')+\'] \',item=data.section.find(selector).eq(0);var selectorImage=".map-container",styleSelectorImage=dataId+selectorImage,itemImage=data.section.find(selectorImage).eq(0),currentImage=CP_Customizer.contentStyle.getNodeProp(itemImage,styleSelectorImage,null,\'background-image\');currentImage=CP_Customizer.utils.normalizeBackgroundImageValue(currentImage);this.getControl(\'contentbgimage\').attachWithSetter(currentImage,function(value){valueimage="url("+value+")";CP_Customizer.contentStyle.setProp(styleSelectorImage,null,\'background-image\',valueimage)})}}}',
  ),
  22 => 
  array (
    'index' => 1031,
    'id' => 'contact-5-materialis',
    'elementId' => 'contact-8',
    'type' => 'section-available',
    'name' => 'Contact',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-contact-5-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/contact-5-materialis.png?v=1551109271',
    'description' => 'Contact',
    'category' => 'contact',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  23 => 
  array (
    'index' => 1032,
    'id' => 'contact-6',
    'elementId' => 'contact-9',
    'type' => 'section-available',
    'name' => 'Contact',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-contact-6.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/contact-6.png?v=1551109271',
    'description' => 'Contact',
    'category' => 'contact',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  24 => 
  array (
    'index' => 1033,
    'id' => 'contact-7',
    'elementId' => 'contact-10',
    'type' => 'section-available',
    'name' => 'Contact',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-contact-7.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/contact-7.png?v=1551109271',
    'description' => 'Contact',
    'category' => 'contact',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canRevertColumnsOnMobile:true,revertClassesHolder:\'.map-col\'}',
  ),
  25 => 
  array (
    'index' => 1034,
    'id' => 'contact-7-materialis',
    'elementId' => 'contact-11',
    'type' => 'section-available',
    'name' => 'Contact',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-contact-7-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/contact-7-materialis.png?v=1551109271',
    'description' => 'Contact',
    'category' => 'contact',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  26 => 
  array (
    'index' => 1035,
    'id' => 'content-1',
    'elementId' => 'content-1',
    'type' => 'section-available',
    'name' => 'Content',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-content-1.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/content-1.png?v=1551109271',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  27 => 
  array (
    'index' => 1036,
    'id' => 'content-1-materialis',
    'elementId' => 'content-2',
    'type' => 'section-available',
    'name' => 'Content',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-content-1-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/content-1-materialis.png?v=1551109271',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  28 => 
  array (
    'index' => 1037,
    'id' => 'content-10',
    'elementId' => 'content-3',
    'type' => 'section-available',
    'name' => 'Content',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-content-10.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/content-10.png?v=1551109271',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canRevertColumnsOnMobile:true}',
  ),
  29 => 
  array (
    'index' => 1038,
    'id' => 'content-10-materialis',
    'elementId' => 'content-4',
    'type' => 'section-available',
    'name' => 'Content',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-content-10-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/content-10-materialis.png?v=1551109271',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  30 => 
  array (
    'index' => 1039,
    'id' => 'content-11',
    'elementId' => 'content-5',
    'type' => 'section-available',
    'name' => 'Content',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-content-11.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/content-11.png?v=1551109271',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  31 => 
  array (
    'index' => 1040,
    'id' => 'content-11-materialis',
    'elementId' => 'content-6',
    'type' => 'section-available',
    'name' => 'Content',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-content-11-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/content-11-materialis.png?v=1551109271',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canRevertColumnsOnMobile:true}',
  ),
  32 => 
  array (
    'index' => 1043,
    'id' => 'content-14',
    'elementId' => 'content-9',
    'type' => 'section-available',
    'name' => 'Content',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-content-14.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/content-14.png?v=1551109271',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  33 => 
  array (
    'index' => 1044,
    'id' => 'content-14-1-materialis',
    'elementId' => 'content-10',
    'type' => 'section-available',
    'name' => 'Content',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-content-14-1-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/content-14-1-materialis.png?v=1551109271',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={customColor:[{colorClass:{selector:\'.padding-first-el\',prefix:\'border-top-\',suffix:\'\'}}]}',
  ),
  34 => 
  array (
    'index' => 1045,
    'id' => 'content-14-materialis',
    'elementId' => 'content-11',
    'type' => 'section-available',
    'name' => 'Content',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-content-14-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/content-14-materialis.png?v=1551109271',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={customColor:[{colorClass:{selector:\'.padding-first-el\',prefix:\'border-top-\',suffix:\'\'}}]}',
  ),
  35 => 
  array (
    'index' => 1046,
    'id' => 'content-15-materialis',
    'elementId' => 'content-12',
    'type' => 'section-available',
    'name' => 'Content',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-content-15-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/content-15-materialis.png?v=1551109271',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  36 => 
  array (
    'index' => 1047,
    'id' => 'content-17',
    'elementId' => 'content-13',
    'type' => 'section-available',
    'name' => 'Content',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-content-17.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/content-17.png?v=1551109271',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'modules.export={contentAligns:[\'[data-type="column"]\'],sectionStyle:{"nomedia":{".overlay-box .overlay-box-offset":{transform:"translate(5%, -5%)",width:"100%",height:"100%"}}}}',
  ),
  37 => 
  array (
    'index' => 1048,
    'id' => 'content-18',
    'elementId' => 'content-14',
    'type' => 'section-available',
    'name' => 'Content',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-content-18.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/content-18.png?v=1551109271',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'modules.export={contentAligns:[\'[data-type="column"]\'],canRevertColumnsOnMobile:true,sectionStyle:{"nomedia":{".overlay-box .overlay-box-offset":{transform:"translate(-5%, -5%)",width:"100%",height:"100%"}}}}',
  ),
  38 => 
  array (
    'index' => 1049,
    'id' => 'content-18-materialis',
    'elementId' => 'content-15',
    'type' => 'section-available',
    'name' => 'Content',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-content-18-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/content-18-materialis.png?v=1551109271',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canRevertColumnsOnMobile:true}',
  ),
  39 => 
  array (
    'index' => 1050,
    'id' => 'content-19',
    'elementId' => 'content-16',
    'type' => 'section-available',
    'name' => 'Content',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-content-19.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/content-19.png?v=1551109271',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  40 => 
  array (
    'index' => 1051,
    'id' => 'content-19-2',
    'elementId' => 'content-17',
    'type' => 'section-available',
    'name' => 'Content',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-content-19-2.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/content-19-2.png?v=1551109271',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canRevertColumnsOnMobile:true}',
  ),
  41 => 
  array (
    'index' => 1052,
    'id' => 'content-3-materialis',
    'elementId' => 'content-18',
    'type' => 'section-available',
    'name' => 'Content',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-content-3-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/content-3-materialis.png?v=1551109271',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  42 => 
  array (
    'index' => 1053,
    'id' => 'content-4-materialis',
    'elementId' => 'content-19',
    'type' => 'section-available',
    'name' => 'Content',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-content-4-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/content-4-materialis.png?v=1551109271',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  43 => 
  array (
    'index' => 1056,
    'id' => 'content-6-2',
    'elementId' => 'content-22',
    'type' => 'section-available',
    'name' => 'Content',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-content-6-2.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/content-6-2.png?v=1551109271',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'modules.export={canRevertColumnsOnMobile:true,canAlignRowItemsContent:false,revertClassesHolder:\'.reverted-class\',allowSectionTitleOptions:true,sectionStyle:{"nomedia":{".overlay-box .overlay-box-offset":{transform:"translate(-10%, 10%)",width:"100%",height:"100%"}}}}',
  ),
  44 => 
  array (
    'index' => 1057,
    'id' => 'content-6-materialis',
    'elementId' => 'content-23',
    'type' => 'section-available',
    'name' => 'Content',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-content-6-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/content-6-materialis.png?v=1551109271',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  45 => 
  array (
    'index' => 1060,
    'id' => 'content-9-2',
    'elementId' => 'content-26',
    'type' => 'section-available',
    'name' => 'Content',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-content-9-2.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/content-9-2.png?v=1551109271',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canRevertColumnsOnMobile:true}',
  ),
  46 => 
  array (
    'index' => 1061,
    'id' => 'content-9-materialis',
    'elementId' => 'content-27',
    'type' => 'section-available',
    'name' => 'Content',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-content-9-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/content-9-materialis.png?v=1551109271',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  47 => 
  array (
    'index' => 1063,
    'id' => 'counters-11-materialis',
    'elementId' => 'counters-2',
    'type' => 'section-available',
    'name' => 'Counters',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-counters-11-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/counters-11-materialis.png?v=1551109271',
    'description' => 'Counters',
    'category' => 'counters',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={customColor:[{colorClass:{selector:\'.counter-box\',prefix:\'bg-\',suffix:\'\'}}]}',
  ),
  48 => 
  array (
    'index' => 1064,
    'id' => 'counters-12-materialis',
    'elementId' => 'counters-3',
    'type' => 'section-available',
    'name' => 'Counters',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-counters-12-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/counters-12-materialis.png?v=1551109271',
    'description' => 'Counters',
    'category' => 'counters',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={customColor:[{colorClass:{selector:\'.counter-text\',prefix:\'\',suffix:\'\'}}]}',
  ),
  49 => 
  array (
    'index' => 1065,
    'id' => 'counters-13-materialis',
    'elementId' => 'counters-4',
    'type' => 'section-available',
    'name' => 'Counters',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-counters-13-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/counters-13-materialis.png?v=1551109271',
    'description' => 'Counters',
    'category' => 'counters',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canAlignRowItemsContent:false,}',
  ),
  50 => 
  array (
    'index' => 1068,
    'id' => 'counters-3-materialis',
    'elementId' => 'counters-7',
    'type' => 'section-available',
    'name' => 'Counters',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-counters-3-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/counters-3-materialis.png?v=1551109271',
    'description' => 'Counters',
    'category' => 'counters',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={customColor:[{colorClass:{selector:\'.counter-text\',prefix:\'\',suffix:\'\'}}]}',
  ),
  51 => 
  array (
    'index' => 1069,
    'id' => 'counters-6-materialis',
    'elementId' => 'counters-8',
    'type' => 'section-available',
    'name' => 'Counters',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-counters-6-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/counters-6-materialis.png?v=1551109271',
    'description' => 'Counters',
    'category' => 'counters',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={customColor:[{colorClass:{selector:\'.counter-text\',prefix:\'\',suffix:\'\'}}]}',
  ),
  52 => 
  array (
    'index' => 1070,
    'id' => 'counters-7-materialis',
    'elementId' => 'counters-9',
    'type' => 'section-available',
    'name' => 'Counters',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-counters-7-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/counters-7-materialis.png?v=1551109271',
    'description' => 'Counters',
    'category' => 'counters',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={customColor:[{colorClass:{selector:\'.counter-text\',prefix:\'\',suffix:\'\'}}]}',
  ),
  53 => 
  array (
    'index' => 1072,
    'id' => 'cta-2-materialis',
    'elementId' => 'cta-2',
    'type' => 'section-available',
    'name' => 'Cta',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-cta-2-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/cta-2-materialis.png?v=1551109271',
    'description' => 'Cta',
    'category' => 'cta',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  54 => 
  array (
    'index' => 1073,
    'id' => 'cta-4-materialis',
    'elementId' => 'cta-3',
    'type' => 'section-available',
    'name' => 'Cta',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-cta-4-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/cta-4-materialis.png?v=1551109271',
    'description' => 'Cta',
    'category' => 'cta',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  55 => 
  array (
    'index' => 1074,
    'id' => 'cta-5-materialis',
    'elementId' => 'cta-4',
    'type' => 'section-available',
    'name' => 'Cta',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-cta-5-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/cta-5-materialis.png?v=1551109271',
    'description' => 'Cta',
    'category' => 'cta',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={sectionArea:{init:function($container){var contentbgcolor=CP_Customizer.createControl.color(this.getPrefixed(\'contentbgcolor\'),$container,{value:\'#ffffff\',label:window.CP_Customizer.translateCompanionString(\'Color Row \')});this.addToControlsList(contentbgcolor)},update:function(data){var dataId=\'[data-id=\'+data.section.attr(\'data-id\')+\'] \',selector=\'.grid-custom\',item=data.section.find(selector).eq(0),styleSelector=dataId+selector,currentColor=CP_Customizer.contentStyle.getNodeProp(item,styleSelector,\':after\',\'background-color\');this.getControl(\'contentbgcolor\').attachWithSetter(currentColor,function(value){CP_Customizer.contentStyle.setProp(styleSelector,\':after\',\'background-color\',value)})}}}',
  ),
  56 => 
  array (
    'index' => 1075,
    'id' => 'cta-6-materialis',
    'elementId' => 'cta-5',
    'type' => 'section-available',
    'name' => 'Cta',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-cta-6-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/cta-6-materialis.png?v=1551109271',
    'description' => 'Cta',
    'category' => 'cta',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  57 => 
  array (
    'index' => 1076,
    'id' => 'cta-7-materialis',
    'elementId' => 'cta-6',
    'type' => 'section-available',
    'name' => 'Cta',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-cta-7-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/cta-7-materialis.png?v=1551109271',
    'description' => 'Cta',
    'category' => 'cta',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  58 => 
  array (
    'index' => 1078,
    'id' => 'cta-centered-bg-section',
    'elementId' => 'cta-8',
    'type' => 'section-available',
    'name' => 'Cta',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-cta-centered-bg-section.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/cta-centered-bg-section.png?v=1551109271',
    'description' => 'Cta',
    'category' => 'cta',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  59 => 
  array (
    'index' => 1079,
    'id' => 'cta-centered-section-grid',
    'elementId' => 'cta-9',
    'type' => 'section-available',
    'name' => 'Cta',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-cta-centered-section-grid.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/cta-centered-section-grid.png?v=1551109271',
    'description' => 'Cta',
    'category' => 'cta',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  60 => 
  array (
    'index' => 1086,
    'id' => 'features-13-materialis',
    'elementId' => 'features-7',
    'type' => 'section-available',
    'name' => 'Features',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-features-13-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/features-13-materialis.png?v=1551109271',
    'description' => 'Features',
    'category' => 'features',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  61 => 
  array (
    'index' => 1087,
    'id' => 'features-15-materialis',
    'elementId' => 'features-8',
    'type' => 'section-available',
    'name' => 'Features',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-features-15-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/features-15-materialis.png?v=1551109271',
    'description' => 'Features',
    'category' => 'features',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  62 => 
  array (
    'index' => 1090,
    'id' => 'features-16-materialis',
    'elementId' => 'features-11',
    'type' => 'section-available',
    'name' => 'Features',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-features-16-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/features-16-materialis.png?v=1551109271',
    'description' => 'Features',
    'category' => 'features',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canAlignRowItemsContent:false}',
  ),
  63 => 
  array (
    'index' => 1091,
    'id' => 'features-3-materialis',
    'elementId' => 'features-12',
    'type' => 'section-available',
    'name' => 'Features',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-features-3-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/features-3-materialis.png?v=1551109271',
    'description' => 'Features',
    'category' => 'features',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  64 => 
  array (
    'index' => 1092,
    'id' => 'features-5-materialis',
    'elementId' => 'features-13',
    'type' => 'section-available',
    'name' => 'Features',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-features-5-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/features-5-materialis.png?v=1551109271',
    'description' => 'Features',
    'category' => 'features',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  65 => 
  array (
    'index' => 1093,
    'id' => 'features-6-materialis',
    'elementId' => 'features-14',
    'type' => 'section-available',
    'name' => 'Features',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-features-6-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/features-6-materialis.png?v=1551109271',
    'description' => 'Features',
    'category' => 'features',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  66 => 
  array (
    'index' => 1094,
    'id' => 'features-8-materialis',
    'elementId' => 'features-15',
    'type' => 'section-available',
    'name' => 'Features',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-features-8-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/features-8-materialis.png?v=1551109271',
    'description' => 'Features',
    'category' => 'features',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canAlignRowItemsContent:false}',
  ),
  67 => 
  array (
    'index' => 1095,
    'id' => 'gallery-1',
    'elementId' => 'gallery-1',
    'type' => 'section-available',
    'name' => 'Gallery',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-gallery-1.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/gallery-1.png?v=1551109271',
    'description' => 'Gallery',
    'category' => 'gallery',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  68 => 
  array (
    'index' => 1096,
    'id' => 'gallery-1-captions',
    'elementId' => 'gallery-2',
    'type' => 'section-available',
    'name' => 'Gallery',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-gallery-1-captions.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/gallery-1-captions.png?v=1551109271',
    'description' => 'Gallery',
    'category' => 'gallery',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  69 => 
  array (
    'index' => 1097,
    'id' => 'gallery-2',
    'elementId' => 'gallery-3',
    'type' => 'section-available',
    'name' => 'Gallery',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-gallery-2.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/gallery-2.png?v=1551109271',
    'description' => 'Gallery',
    'category' => 'gallery',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  70 => 
  array (
    'index' => 1098,
    'id' => 'gallery-3',
    'elementId' => 'gallery-4',
    'type' => 'section-available',
    'name' => 'Gallery',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-gallery-3.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/gallery-3.png?v=1551109271',
    'description' => 'Gallery',
    'category' => 'gallery',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  71 => 
  array (
    'index' => 1101,
    'id' => 'latest-news-2-materialis',
    'elementId' => 'latest-news-2',
    'type' => 'section-available',
    'name' => 'Latest-news',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-latest-news-2-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/latest-news-2-materialis.png?v=1551109271',
    'description' => 'Latest-news',
    'category' => 'latest_news',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  72 => 
  array (
    'index' => 1102,
    'id' => 'latest-news-3-materialis',
    'elementId' => 'latest-news-3',
    'type' => 'section-available',
    'name' => 'Latest-news',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-latest-news-3-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/latest-news-3-materialis.png?v=1551109271',
    'description' => 'Latest-news',
    'category' => 'latest_news',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  73 => 
  array (
    'index' => 1103,
    'id' => 'latest-news-4-materialis',
    'elementId' => 'latest-news-4',
    'type' => 'section-available',
    'name' => 'Latest-news',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-latest-news-4-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/latest-news-4-materialis.png?v=1551109271',
    'description' => 'Latest-news',
    'category' => 'latest_news',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  74 => 
  array (
    'index' => 1104,
    'id' => 'overlappable-10-materialis',
    'elementId' => 'overlappable-1',
    'type' => 'section-available',
    'name' => 'Overlappable',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-overlappable-10-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/overlappable-10-materialis.png?v=1551109271',
    'description' => 'Overlappable',
    'category' => 'overlappable',
    'prepend' => true,
    'pro-only' => true,
    'export' => 'module.exports={allowSectionTitleOptions:false,afterInsert:function(){CP_Customizer.setMod(\'header_overlap_with\',\'95px\')}}',
  ),
  75 => 
  array (
    'index' => 1105,
    'id' => 'overlappable-11-materialis',
    'elementId' => 'overlappable-2',
    'type' => 'section-available',
    'name' => 'Overlappable',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-overlappable-11-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/overlappable-11-materialis.png?v=1551109271',
    'description' => 'Overlappable',
    'category' => 'overlappable',
    'prepend' => true,
    'pro-only' => true,
    'export' => 'module.exports={allowSectionTitleOptions:false,afterInsert:function(){CP_Customizer.setMod(\'header_overlap_with\',\'95px\')},customColor:[{colorClass:{selector:\'div[class*="bg-"]\',prefix:\'bg-\',suffix:\'\'}}]}',
  ),
  76 => 
  array (
    'index' => 1107,
    'id' => 'overlappable-2',
    'elementId' => 'overlappable-4',
    'type' => 'section-available',
    'name' => 'Overlappable',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-overlappable-2.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/overlappable-2.png?v=1551109271',
    'description' => 'Overlappable',
    'category' => 'overlappable',
    'prepend' => true,
    'pro-only' => true,
    'export' => 'module.exports={allowSectionTitleOptions:false,afterInsert:function(){CP_Customizer.setMod(\'header_overlap_with\',\'95px\')}}',
  ),
  77 => 
  array (
    'index' => 1108,
    'id' => 'overlappable-3',
    'elementId' => 'overlappable-5',
    'type' => 'section-available',
    'name' => 'Overlappable',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-overlappable-3.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/overlappable-3.png?v=1551109271',
    'description' => 'Overlappable',
    'category' => 'overlappable',
    'prepend' => true,
    'pro-only' => true,
    'export' => 'module.exports={allowSectionTitleOptions:false,afterInsert:function(){CP_Customizer.setMod(\'header_overlap_with\',\'95px\')}}',
  ),
  78 => 
  array (
    'index' => 1110,
    'id' => 'overlappable-4-materialis',
    'elementId' => 'overlappable-7',
    'type' => 'section-available',
    'name' => 'Overlappable',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-overlappable-4-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/overlappable-4-materialis.png?v=1551109271',
    'description' => 'Overlappable',
    'category' => 'overlappable',
    'prepend' => true,
    'pro-only' => true,
    'export' => 'module.exports={allowSectionTitleOptions:false,afterInsert:function(){CP_Customizer.setMod(\'header_overlap_with\',\'70px\')},customColorDefault:\'#2987E2\',customColor:[{colorClass:{selector:\'.coloured-box\',prefix:\'bg-\',suffix:\'\'}}]}',
  ),
  79 => 
  array (
    'index' => 1112,
    'id' => 'overlappable-9-materialis',
    'elementId' => 'overlappable-9',
    'type' => 'section-available',
    'name' => 'Overlappable',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-overlappable-9-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/overlappable-9-materialis.png?v=1551109271',
    'description' => 'Overlappable',
    'category' => 'overlappable',
    'prepend' => true,
    'pro-only' => true,
    'export' => 'module.exports={allowSectionTitleOptions:false,afterInsert:function(){CP_Customizer.setMod(\'header_overlap_with\',\'95px\')}}',
  ),
  80 => 
  array (
    'index' => 1113,
    'id' => 'portfolio-1',
    'elementId' => 'portfolio-1',
    'type' => 'section-available',
    'name' => 'Portfolio',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-portfolio-1.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/portfolio-1.png?v=1551109271',
    'description' => 'Portfolio',
    'category' => 'portfolio',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canAlignRowItemsContent:false,customColor:[{colorClass:{selector:\'.overlay\',prefix:\'grad-180-transparent-\',suffix:\'\'}}]}',
  ),
  81 => 
  array (
    'index' => 1116,
    'id' => 'portfolio-4-materialis',
    'elementId' => 'portfolio-4',
    'type' => 'section-available',
    'name' => 'Portfolio',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-portfolio-4-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/portfolio-4-materialis.png?v=1551109271',
    'description' => 'Portfolio',
    'category' => 'portfolio',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  82 => 
  array (
    'index' => 1117,
    'id' => 'portfolio-5-materialis',
    'elementId' => 'portfolio-5',
    'type' => 'section-available',
    'name' => 'Portfolio',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-portfolio-5-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/portfolio-5-materialis.png?v=1551109271',
    'description' => 'Portfolio',
    'category' => 'portfolio',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  83 => 
  array (
    'index' => 1118,
    'id' => 'portfolio-6',
    'elementId' => 'portfolio-6',
    'type' => 'section-available',
    'name' => 'Portfolio',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-portfolio-6.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/portfolio-6.png?v=1551109271',
    'description' => 'Portfolio',
    'category' => 'portfolio',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={customColor:[{colorClass:{selector:\'div[class*="bg-"]\',prefix:\'bg-\',suffix:\'\'}}]}',
  ),
  84 => 
  array (
    'index' => 1119,
    'id' => 'portfolio-6-materialis',
    'elementId' => 'portfolio-7',
    'type' => 'section-available',
    'name' => 'Portfolio',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-portfolio-6-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/portfolio-6-materialis.png?v=1551109271',
    'description' => 'Portfolio',
    'category' => 'portfolio',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  85 => 
  array (
    'index' => 1120,
    'id' => 'pricing-1',
    'elementId' => 'pricing-1',
    'type' => 'section-available',
    'name' => 'Pricing',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-pricing-1.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/pricing-1.png?v=1551109271',
    'description' => 'Pricing',
    'category' => 'pricing',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canAlignRowItemsContent:false,customColor:[{colorClass:{selector:".button",prefix:\'\',suffix:\'\'}},{colorClass:{selector:"p.custom-color",prefix:\'\',suffix:\'\'}}]}',
  ),
  86 => 
  array (
    'index' => 1121,
    'id' => 'pricing-10-materialis',
    'elementId' => 'pricing-2',
    'type' => 'section-available',
    'name' => 'Pricing',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-pricing-10-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/pricing-10-materialis.png?v=1551109271',
    'description' => 'Pricing',
    'category' => 'pricing',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canAlignRowItemsContent:false,showFeaturedCheckbox:false,customColor:[{colorClass:{selector:".icon",prefix:\'\',suffix:\'\'}},{colorClass:{selector:".button",prefix:\'\',suffix:\'\'}},{colorClass:{selector:".first-div",prefix:\'bg-\',suffix:\'\'}},]}',
  ),
  87 => 
  array (
    'index' => 1122,
    'id' => 'pricing-2',
    'elementId' => 'pricing-3',
    'type' => 'section-available',
    'name' => 'Pricing',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-pricing-2.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/pricing-2.png?v=1551109271',
    'description' => 'Pricing',
    'category' => 'pricing',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canAlignRowItemsContent:false,customColor:[{colorClass:{selector:\'.card\',prefix:\'bg-\',suffix:\'\'}}]}',
  ),
  88 => 
  array (
    'index' => 1123,
    'id' => 'pricing-2-materialis',
    'elementId' => 'pricing-4',
    'type' => 'section-available',
    'name' => 'Pricing',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-pricing-2-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/pricing-2-materialis.png?v=1551109271',
    'description' => 'Pricing',
    'category' => 'pricing',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canAlignRowItemsContent:false,customColor:[{colorClass:{selector:".button",prefix:\'\',suffix:\'\'}},{colorClass:{selector:".top-right-triangle",prefix:\'\',suffix:\'\'}},{colorClass:{selector:".change-color",prefix:\'\',suffix:\'\'}},{colorClass:{selector:".icon",prefix:\'\',suffix:\'\'}},]}',
  ),
  89 => 
  array (
    'index' => 1124,
    'id' => 'pricing-3',
    'elementId' => 'pricing-5',
    'type' => 'section-available',
    'name' => 'Pricing',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-pricing-3.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/pricing-3.png?v=1551109271',
    'description' => 'Pricing',
    'category' => 'pricing',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canAlignRowItemsContent:false,customColor:[{colorClass:{selector:".button",prefix:\'\',suffix:\'\'}},{colorClass:{selector:".top-right-triangle",prefix:\'\',suffix:\'\'}},{colorClass:{selector:".pay-per",prefix:\'\',suffix:\'\'}}]}',
  ),
  90 => 
  array (
    'index' => 1125,
    'id' => 'pricing-4',
    'elementId' => 'pricing-6',
    'type' => 'section-available',
    'name' => 'Pricing',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-pricing-4.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/pricing-4.png?v=1551109271',
    'description' => 'Pricing',
    'category' => 'pricing',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canAlignRowItemsContent:false,customColor:[{colorClass:{selector:".button",prefix:\'\',suffix:\'\'}},{colorClass:{selector:".icon",prefix:\'\',suffix:\'\'}},{colorClass:{selector:".top-right-triangle",prefix:\'\',suffix:\'\'}}]}',
  ),
  91 => 
  array (
    'index' => 1126,
    'id' => 'pricing-4-materialis',
    'elementId' => 'pricing-7',
    'type' => 'section-available',
    'name' => 'Pricing',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-pricing-4-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/pricing-4-materialis.png?v=1551109271',
    'description' => 'Pricing',
    'category' => 'pricing',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canAlignRowItemsContent:false,customColor:[{colorClass:{selector:".button",prefix:\'\',suffix:\'\'}},{colorClass:{selector:".tag-buy",prefix:\'bg-\',suffix:\'\'}},{colorClass:{selector:".change-color",prefix:\'\',suffix:\'\'}}]}',
  ),
  92 => 
  array (
    'index' => 1127,
    'id' => 'pricing-5',
    'elementId' => 'pricing-8',
    'type' => 'section-available',
    'name' => 'Pricing',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-pricing-5.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/pricing-5.png?v=1551109271',
    'description' => 'Pricing',
    'category' => 'pricing',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canAlignRowItemsContent:false}',
  ),
  93 => 
  array (
    'index' => 1128,
    'id' => 'pricing-5-materialis',
    'elementId' => 'pricing-9',
    'type' => 'section-available',
    'name' => 'Pricing',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-pricing-5-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/pricing-5-materialis.png?v=1551109271',
    'description' => 'Pricing',
    'category' => 'pricing',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canAlignRowItemsContent:false}',
  ),
  94 => 
  array (
    'index' => 1129,
    'id' => 'pricing-6',
    'elementId' => 'pricing-10',
    'type' => 'section-available',
    'name' => 'Pricing',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-pricing-6.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/pricing-6.png?v=1551109271',
    'description' => 'Pricing',
    'category' => 'pricing',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canAlignRowItemsContent:false,customColor:[{colorClass:{selector:\'.card\',prefix:\'card-\',suffix:\'\'}}]}',
  ),
  95 => 
  array (
    'index' => 1130,
    'id' => 'pricing-7',
    'elementId' => 'pricing-11',
    'type' => 'section-available',
    'name' => 'Pricing',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-pricing-7.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/pricing-7.png?v=1551109271',
    'description' => 'Pricing',
    'category' => 'pricing',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canAlignRowItemsContent:false}',
  ),
  96 => 
  array (
    'index' => 1131,
    'id' => 'pricing-8-materialis',
    'elementId' => 'pricing-12',
    'type' => 'section-available',
    'name' => 'Pricing',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-pricing-8-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/pricing-8-materialis.png?v=1551109271',
    'description' => 'Pricing',
    'category' => 'pricing',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canAlignRowItemsContent:false,customColor:[{colorClass:{selector:\'.rectangle\',prefix:\'bg-\',suffix:\'\'}}]}',
  ),
  97 => 
  array (
    'index' => 1132,
    'id' => 'pricing-9-materialis',
    'elementId' => 'pricing-13',
    'type' => 'section-available',
    'name' => 'Pricing',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-pricing-9-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/pricing-9-materialis.png?v=1551109271',
    'description' => 'Pricing',
    'category' => 'pricing',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canAlignRowItemsContent:false,customColor:[{colorClass:{selector:\'.card\',prefix:\'border-\',suffix:\'\'}},{colorClass:{selector:\'.icon\',prefix:\'\',suffix:\'\'}},{colorClass:{selector:\'.button\',prefix:\'\',suffix:\'\'}}]}',
  ),
  98 => 
  array (
    'index' => 1133,
    'id' => 'subscribe-12-materialis',
    'elementId' => 'subscribe-1',
    'type' => 'section-available',
    'name' => 'Subscribe',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-subscribe-12-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/subscribe-12-materialis.png?v=1551109271',
    'description' => 'Subscribe',
    'category' => 'subscribe',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  99 => 
  array (
    'index' => 1134,
    'id' => 'subscribe-13-materialis',
    'elementId' => 'subscribe-2',
    'type' => 'section-available',
    'name' => 'Subscribe',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-subscribe-13-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/subscribe-13-materialis.png?v=1551109271',
    'description' => 'Subscribe',
    'category' => 'subscribe',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  100 => 
  array (
    'index' => 1135,
    'id' => 'subscribe-14-materialis',
    'elementId' => 'subscribe-3',
    'type' => 'section-available',
    'name' => 'Subscribe',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-subscribe-14-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/subscribe-14-materialis.png?v=1551109271',
    'description' => 'Subscribe',
    'category' => 'subscribe',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  101 => 
  array (
    'index' => 1136,
    'id' => 'subscribe-2cols-section',
    'elementId' => 'subscribe-4',
    'type' => 'section-available',
    'name' => 'Subscribe',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-subscribe-2cols-section.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/subscribe-2cols-section.png?v=1551109271',
    'description' => 'Subscribe',
    'category' => 'subscribe',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  102 => 
  array (
    'index' => 1137,
    'id' => 'subscribe-centered-section',
    'elementId' => 'subscribe-5',
    'type' => 'section-available',
    'name' => 'Subscribe',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-subscribe-centered-section.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/subscribe-centered-section.png?v=1551109271',
    'description' => 'Subscribe',
    'category' => 'subscribe',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  103 => 
  array (
    'index' => 1138,
    'id' => 'subscribe-social-section',
    'elementId' => 'subscribe-6',
    'type' => 'section-available',
    'name' => 'Subscribe',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-subscribe-social-section.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/subscribe-social-section.png?v=1551109271',
    'description' => 'Subscribe',
    'category' => 'subscribe',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  104 => 
  array (
    'index' => 1140,
    'id' => 'team-2-materialis',
    'elementId' => 'team-2',
    'type' => 'section-available',
    'name' => 'Team',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-team-2-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/team-2-materialis.png?v=1551109271',
    'description' => 'Team',
    'category' => 'team',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  105 => 
  array (
    'index' => 1141,
    'id' => 'team-3-materialis',
    'elementId' => 'team-3',
    'type' => 'section-available',
    'name' => 'Team',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-team-3-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/team-3-materialis.png?v=1551109271',
    'description' => 'Team',
    'category' => 'team',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={customColorDefault:\'#000000\',customColor:[{colorClass:{selector:\'[data-hover-fx] .overlay\',prefix:\'grad-180-transparent-\',suffix:\'\'}}]}',
  ),
  106 => 
  array (
    'index' => 1142,
    'id' => 'team-4-materialis',
    'elementId' => 'team-4',
    'type' => 'section-available',
    'name' => 'Team',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-team-4-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/team-4-materialis.png?v=1551109271',
    'description' => 'Team',
    'category' => 'team',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  107 => 
  array (
    'index' => 1143,
    'id' => 'team-5-materialis',
    'elementId' => 'team-5',
    'type' => 'section-available',
    'name' => 'Team',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-team-5-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/team-5-materialis.png?v=1551109271',
    'description' => 'Team',
    'category' => 'team',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  108 => 
  array (
    'index' => 1144,
    'id' => 'team-6-materialis',
    'elementId' => 'team-6',
    'type' => 'section-available',
    'name' => 'Team',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-team-6-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/team-6-materialis.png?v=1551109271',
    'description' => 'Team',
    'category' => 'team',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={customColorDefault:\'#000000\',customColor:[{colorClass:{selector:\'[data-hover-fx] .content-holder\',prefix:\'bg-\',suffix:\'\'}}]}',
  ),
  109 => 
  array (
    'index' => 1146,
    'id' => 'team-9-materialis',
    'elementId' => 'team-8',
    'type' => 'section-available',
    'name' => 'Team',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-team-9-materialis.png?v=1551109272',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/team-9-materialis.png?v=1551109272',
    'description' => 'Team',
    'category' => 'team',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  110 => 
  array (
    'index' => 1147,
    'id' => 'testimonials-1',
    'elementId' => 'testimonials-1',
    'type' => 'section-available',
    'name' => 'Testimonials',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-testimonials-1.png?v=1551109272',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/testimonials-1.png?v=1551109272',
    'description' => 'Testimonials',
    'category' => 'testimonials',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  111 => 
  array (
    'index' => 1149,
    'id' => 'testimonials-11-materialis',
    'elementId' => 'testimonials-3',
    'type' => 'section-available',
    'name' => 'Testimonials',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-testimonials-11-materialis.png?v=1551109272',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/testimonials-11-materialis.png?v=1551109272',
    'description' => 'Testimonials',
    'category' => 'testimonials',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  112 => 
  array (
    'index' => 1150,
    'id' => 'testimonials-13-materialis',
    'elementId' => 'testimonials-4',
    'type' => 'section-available',
    'name' => 'Testimonials',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-testimonials-13-materialis.png?v=1551109272',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/testimonials-13-materialis.png?v=1551109272',
    'description' => 'Testimonials',
    'category' => 'testimonials',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  113 => 
  array (
    'index' => 1151,
    'id' => 'testimonials-14-materialis',
    'elementId' => 'testimonials-5',
    'type' => 'section-available',
    'name' => 'Testimonials',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-testimonials-14-materialis.png?v=1551109272',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/testimonials-14-materialis.png?v=1551109272',
    'description' => 'Testimonials',
    'category' => 'testimonials',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  114 => 
  array (
    'index' => 1154,
    'id' => 'testimonials-6-materialis',
    'elementId' => 'testimonials-8',
    'type' => 'section-available',
    'name' => 'Testimonials',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-testimonials-6-materialis.png?v=1551109272',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/testimonials-6-materialis.png?v=1551109272',
    'description' => 'Testimonials',
    'category' => 'testimonials',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  115 => 
  array (
    'index' => 1155,
    'id' => 'testimonials-7-materialis',
    'elementId' => 'testimonials-9',
    'type' => 'section-available',
    'name' => 'Testimonials',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-testimonials-7-materialis.png?v=1551109272',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/testimonials-7-materialis.png?v=1551109272',
    'description' => 'Testimonials',
    'category' => 'testimonials',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  116 => 
  array (
    'index' => 1156,
    'id' => 'woocommerce-section-1',
    'elementId' => 'woocommerce-1',
    'type' => 'section-available',
    'name' => 'Woocommerce',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-woocommerce-section-1.png?v=1551109272',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/woocommerce-section-1.png?v=1551109272',
    'description' => 'Woocommerce',
    'category' => 'woocommerce',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  117 => 
  array (
    'index' => 1157,
    'id' => 'woocommerce-section-2',
    'elementId' => 'woocommerce-2',
    'type' => 'section-available',
    'name' => 'Woocommerce',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-woocommerce-section-2.png?v=1551109272',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/woocommerce-section-2.png?v=1551109272',
    'description' => 'Woocommerce',
    'category' => 'woocommerce',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={sectionArea:{areaTitle:window.CP_Customizer.translateCompanionString("WooCommerce Section Options"),init:function($container){var overlayColor=CP_Customizer.createControl.color(this.getPrefixed(\'overlayColor\'),$container,{value:\'#ffffff\',label:window.CP_Customizer.translateCompanionString(\'Overlay color\')});var priceBGColor=CP_Customizer.createControl.color(this.getPrefixed(\'priceBGColor\'),$container,{value:\'#ffffff\',label:window.CP_Customizer.translateCompanionString(\'Price Background color\')});var titleColor=CP_Customizer.createControl.color(this.getPrefixed(\'titleColor\'),$container,{value:\'#ffffff\',label:window.CP_Customizer.translateCompanionString(\'Title color\'),alpha:\'false\',});var priceColor=CP_Customizer.createControl.color(this.getPrefixed(\'priceColor\'),$container,{value:\'#ffffff\',label:window.CP_Customizer.translateCompanionString(\'Price color\'),alpha:\'false\'});this.addToControlsList(overlayColor);this.addToControlsList(priceBGColor);this.addToControlsList(titleColor);this.addToControlsList(priceColor)},update:function(data){var dataId=\'[data-id=\'+data.section.attr(\'data-id\')+\'] .woocommerce.in-section ul.products\',overlaySelector=\' li.product .contentswap-effect .overlay\',priceBGSelector=\' li.product .swap-inner .price\',titleSelector=\' li.product .swap-inner h4\',priceSelector=\' li.product .swap-inner .price .amount\',overlayItem=data.section.find(overlaySelector).eq(0),priceItem=data.section.find(priceBGSelector).eq(0),titleItem=data.section.find(titleSelector).eq(0),priceTextItem=data.section.find(priceSelector).eq(0),overlayStyleSelector=dataId+overlaySelector,priceBGStyleSelector=dataId+priceBGSelector,titleStyleSelector=dataId+titleSelector,priceStyleSelector=dataId+priceSelector,currentOverlayGradient=CP_Customizer.contentStyle.getNodeProp(overlayItem,overlayStyleSelector,null,\'background\'),currentOverlayColor=CP_Customizer.styleUtils.getCSSGradientColors(currentOverlayGradient,true).pop().value.toHexString(),currentPriceBGColor=CP_Customizer.contentStyle.getNodeProp(priceItem,priceBGStyleSelector,null,\'background\'),currentTitleColor=CP_Customizer.contentStyle.getNodeProp(titleItem,titleStyleSelector,null,\'color\'),currentPriceColor=CP_Customizer.contentStyle.getNodeProp(priceTextItem,priceStyleSelector,null,\'color\');this.getControl(\'overlayColor\').attachWithSetter(currentOverlayColor,function(value){var opacity=CP_Customizer.styleUtils.getRGBAStringTransparency(value);value=CP_Customizer.styleUtils.generateOneSideLinerGradient(180,value);CP_Customizer.contentStyle.setProp(overlayStyleSelector,null,\'background\',value);CP_Customizer.contentStyle.setProp(overlayStyleSelector,null,\'opacity\',opacity)});this.getControl(\'priceBGColor\').attachWithSetter(currentPriceBGColor,function(value){CP_Customizer.contentStyle.setProp(priceBGStyleSelector,null,\'background\',value)});this.getControl(\'titleColor\').attachWithSetter(currentTitleColor,function(value){CP_Customizer.contentStyle.setProp(titleStyleSelector,null,\'color\',value)});this.getControl(\'priceColor\').attachWithSetter(currentPriceColor,function(value){CP_Customizer.contentStyle.setProp(priceStyleSelector,null,\'color\',value)})}}}',
  ),
  118 => 
  array (
    'index' => 1158,
    'id' => 'woocommerce-section-3',
    'elementId' => 'woocommerce-3',
    'type' => 'section-available',
    'name' => 'Woocommerce',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-woocommerce-section-3.png?v=1551109272',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/woocommerce-section-3.png?v=1551109272',
    'description' => 'Woocommerce',
    'category' => 'woocommerce',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  119 => 
  array (
    'index' => 1159,
    'id' => 'woocommerce-section-4',
    'elementId' => 'woocommerce-4',
    'type' => 'section-available',
    'name' => 'Woocommerce',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-woocommerce-section-4.png?v=1551109272',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/woocommerce-section-4.png?v=1551109272',
    'description' => 'Woocommerce',
    'category' => 'woocommerce',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  120 => 
  array (
    'index' => 1160,
    'id' => 'woocommerce-section-5',
    'elementId' => 'woocommerce-5',
    'type' => 'section-available',
    'name' => 'Woocommerce',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-woocommerce-section-5.png?v=1551109272',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/woocommerce-section-5.png?v=1551109272',
    'description' => 'Woocommerce',
    'category' => 'woocommerce',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
);
