<?php

return array (
  0 => 
  array (
    'index' => 1001,
    'id' => 'about-1',
    'elementId' => 'about-1',
    'type' => 'section-available',
    'name' => 'About',
    'content' => '<div data-label="About" data-id="about-1" data-export-id="about-1" data-category="about" class="about-1 content-section content-section-spacing-large"><div class="gridContainer"> <div class="row col-xs-12"><div class="section-title-col" data-type="column"> <h5>LOREM IPSUM DOLOR</h5> <h2>Brand new WordPress theme&nbsp;<span href="#" style="font-weight:700;font-family:Playfair Display,sans-serif;font-style:italic;">with unlimited power</span>&nbsp;and customization possibilities<br></h2> <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.</p></div> </div> <div class="row col-xs-12"> <div class="button-holder space-bottom space-bottom-small" data-type="column"> <a class="button big color1 font-500" href="#">GET STARTED NOW</a></div> <div class="col-xs bottom-xs flexbox image-group-bottom-3-img center-xs"> <img class="left-img mdc-elevation--z10 rounded-topleft-topright" data-size="400x275" src="[tag_companion_uri]/sections/images/computer-2569652.jpg"> <img class="center-img mdc-elevation--z10 rounded-topleft-topright" data-size="500x325" src="[tag_companion_uri]/sections/images/apple-1838564.jpg"> <img class="right-img mdc-elevation--z10 rounded-topleft-topright" data-size="400x275" src="[tag_companion_uri]/sections/images/laptop-2559795.jpg"></div> </div></div> </div>',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-about-1.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/about-1.png?v=1551109271',
    'description' => 'About',
    'category' => 'about',
    'prepend' => false,
    'pro' => false,
    'export' => 'modules.export={contentAligns:[\'[data-type="column"]\']}',
  ),
  1 => 
  array (
    'index' => 1002,
    'id' => 'about-10',
    'elementId' => 'about-2',
    'type' => 'section-available',
    'name' => 'About',
    'content' => '<div data-label="About" data-id="about-10" data-export-id="about-10" data-category="about" class="about-10 content-section content-section-spacing-large"><div class="gridContainer"> <div class="row middle-sm text-center"><div class="col-sm-5 space-bottom-xs content-column" data-type="column"> <h5>LOREM IPSUM DOLOR</h5> <h2>Enjoy the best <br/> <span style="font-family:Playfair Display,sans-serif;font-weight:700;font-style:italic;" href="#">design and functions</span> combined together</h2> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p> <a class="button big color1" href="#">GET STARTED NOW</a></div> <div class="col-sm-7 flexbox middle-xs center-xs"><div class="overlay-box middle-xs center-xs flexbox box-image"> <div class="overlay-box-offset offset-border mdc-elevation--z5 border-color1 hide-xs border-radius-8"></div> <img class="mdc-elevation--z10 rounded max-image" data-size="480x700" src="[tag_companion_uri]/sections/images/about-img-5.jpg"/></div> </div></div> </div></div>',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-about-10.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/about-10.png?v=1551109271',
    'description' => 'About',
    'category' => 'about',
    'prepend' => false,
    'pro' => false,
    'export' => 'module.exports={contentAligns:[\'[data-type="column"]\'],sectionStyle:{"nomedia":{".overlay-box .overlay-box-offset":{transform:"translate(15%, 5%)",width:"100%",height:"100%","z-index":-1}}}}',
  ),
  2 => 
  array (
    'index' => 1006,
    'id' => 'about-4',
    'elementId' => 'about-6',
    'type' => 'section-available',
    'name' => 'About',
    'content' => '<div data-label="About" data-id="about-4" data-export-id="about-4" data-category="about" class="about-4 content-section content-section-spacing-large"><div class="gridContainer"> <div class="row middle-sm text-center"><div class="col-sm-5 space-bottom-xs " data-type="column"> <h5>LOREM IPSUM DOLOR</h5> <h2>Enjoy the best <br/> <span style="font-family:Playfair Display,sans-serif;font-weight:700;font-style:italic;" href="#">design and functions</span> combined together</h2> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p> <a class="button big color1" href="#">GET STARTED NOW</a></div> <div class="col-sm-7 flexbox center-xs middle-xs image-group-2-img padding-top-bottom"> <img class="img-1 rounded mdc-elevation--z10" data-size="250x200" src="[tag_companion_uri]/sections/images/apple-1838564.jpg"/> <img class="img-2 rounded mdc-elevation--z10" data-size="220x170" src="[tag_companion_uri]/sections/images/computer-2569652.jpg"/></div> </div></div> </div>',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-about-4.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/about-4.png?v=1551109271',
    'description' => 'About',
    'category' => 'about',
    'prepend' => false,
    'pro' => false,
    'export' => 'modules.export={contentAligns:[\'[data-type="column"]\']}',
  ),
  3 => 
  array (
    'index' => 1013,
    'id' => 'about-9',
    'elementId' => 'about-13',
    'type' => 'section-available',
    'name' => 'About',
    'content' => '<div data-label="About" data-id="about-9" data-export-id="about-9" data-category="about" class="about-9 content-section content-section-spacing-large"><div class="gridContainer"> <div class="row middle-sm text-center"><div class="col-sm-5 space-bottom-xs content-column content-right-sm" data-type="column"> <h5>LOREM IPSUM DOLOR</h5> <h2>Enjoy the best <br/> <span style="font-family:Playfair Display,sans-serif;font-weight:700;font-style:italic;" href="#">design and functions</span> combined together</h2> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p> <a class="button big color1" href="#">GET STARTED NOW</a></div> <div class="col-sm-7 flexbox flexbox middle-xs center-xs"><div class="overlay-box flexbox middle-xs center-xs overlay-holder "> <div class="overlay-box-offset offset-background mdc-elevation--z5 bg-color2 hide-xs border-radius-8"></div> <img class="flexbox mdc-elevation--z10 img1 rounded" src="[tag_companion_uri]/sections/images/urban-438393.jpg"/></div> </div></div> </div></div>',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-about-9.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/about-9.png?v=1551109271',
    'description' => 'About',
    'category' => 'about',
    'prepend' => false,
    'pro' => false,
    'export' => 'module.exports={contentAligns:[\'[data-type="column"]\'],sectionStyle:{"nomedia":{".overlay-box .overlay-box-offset":{transform:"translate(31%,-8%)",width:"83%",height:"113%"}}}}',
  ),
  4 => 
  array (
    'index' => 1015,
    'id' => 'about-images-right-section',
    'elementId' => 'about-15',
    'type' => 'section-available',
    'name' => 'About',
    'content' => '<div data-label="About" data-id="about-images-right-section" data-export-id="about-images-right-section" data-category="about" class="about-images-right-section content-section content-section-spacing-large"><div class="gridContainer"> <div class="row middle-sm text-center"><div class="col-sm-5 content-left-sm space-bottom-xs" data-type="column"> <h5>LOREM IPSUM DOLOR</h5> <h2>Enjoy the best <br/> <span style="font-family:Playfair Display,sans-serif;font-weight:700;font-style:italic;" href="#">design and functions</span> combined together</h2> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p> <a class="button big color1" href="#">GET STARTED NOW</a></div> <div class="col-sm-7 image-group-side-3-img"> <img class="topimg mdc-elevation--z10 rounded" src="[tag_companion_uri]/sections/images/people-2605526.jpg"/> <img class="rightimg mdc-elevation--z10 rounded" src="[tag_companion_uri]/sections/images/background-2498615.jpg"/> <div class="leftimg"> <img class="mdc-elevation--z10 rounded" src="[tag_companion_uri]/sections/images/woman-1209584.jpg"/></div> </div></div> </div></div>',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-about-images-right-section.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/about-images-right-section.png?v=1551109271',
    'description' => 'About',
    'category' => 'about',
    'prepend' => false,
    'pro' => false,
    'export' => 'module.exports={contentAligns:[\'[data-type="column"]\'],flexAligns:[\'.image-group-side-3-img\']}',
  ),
  5 => 
  array (
    'index' => 1018,
    'id' => 'clients-2',
    'elementId' => 'clients-2',
    'type' => 'section-available',
    'name' => 'Clients',
    'content' => '<div data-label="Clients" data-id="clients-2" data-export-id="clients-2" data-category="clients" class="clients-2 content-section content-section-spacing-large"><div class="gridContainer"> <div class="row"><div class="section-title-col" data-type="column"> <h2 class="font-700">Our Happy Clients</h2> <p class="lead">A Right Media Mix Can Make The Difference</p></div> </div> <div class="row center-xs spaced-cols middle-sm" data-type="row"> <div class="col-xs-6 col-sm-3"> <img src="[tag_companion_uri]/sections/images/logo1.png"/></div> <div class="col-xs-6 col-sm-3"> <img src="[tag_companion_uri]/sections/images/logo2.png"/></div> <div class="col-xs-6 col-sm-3"> <img src="[tag_companion_uri]/sections/images/logo3.png"/></div> <div class="col-xs-6 col-sm-3"> <img src="[tag_companion_uri]/sections/images/logo4.png"/></div> </div></div> </div>',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-clients-2.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/clients-2.png?v=1551109271',
    'description' => 'Clients',
    'category' => 'clients',
    'prepend' => false,
    'pro' => false,
    'export' => 'module.exports={canAlignRowItemsContent:false}',
  ),
  6 => 
  array (
    'index' => 1019,
    'id' => 'clients-2-materialis',
    'elementId' => 'clients-3',
    'type' => 'section-available',
    'name' => 'Clients',
    'content' => '<div data-label="Clients" data-id="clients-2-materialis" data-export-id="clients-2-materialis" data-category="clients" class="clients-2-materialis content-section content-section-spacing-large"><div class="gridContainer"> <div class="row"><div class="section-title-col" data-type="column"> <h2>Our Clients</h2> <p class="lead">If you’re looking for the latest in wireless headphones for your enjoyment and private listening, whether to TV, stereo, home entertainment such as theater, iTunes or Ipod.</p></div> </div> <div class="row spaced-cols center-sm" data-type="row" data-fixed="true"> <div class="col-xs-12 col-sm-3"> <div class="card mdc-elevation--z3"> <div class="flexbox image-holder middle-sm center-xs" data-type="column"> <img class="" src="[tag_companion_uri]/sections/images/bw-logo-1.png"/></div> </div></div> <div class="col-xs-12 col-sm-3"><div class="card mdc-elevation--z3"> <div class="flexbox image-holder middle-sm center-xs" data-type="column"> <img class="" src="[tag_companion_uri]/sections/images/bw-logo-2.png"/></div> </div></div> <div class="col-xs-12 col-sm-3"><div class="card mdc-elevation--z3"> <div class="flexbox image-holder middle-sm center-xs" data-type="column"> <img class="" src="[tag_companion_uri]/sections/images/bw-logo-3.png"/></div> </div></div> <div class="col-xs-12 col-sm-3"><div class="card mdc-elevation--z3"> <div class="flexbox image-holder middle-sm center-xs" data-type="column"> <img class="" src="[tag_companion_uri]/sections/images/bw-logo-4.png"/></div> </div></div> <div class="col-xs-12 col-sm-3"><div class="card mdc-elevation--z3"> <div class="flexbox image-holder middle-sm center-xs" data-type="column"> <img class="" src="[tag_companion_uri]/sections/images/bw-logo-1.png"/></div> </div></div> <div class="col-xs-12 col-sm-3"><div class="card mdc-elevation--z3"> <div class="flexbox image-holder middle-sm center-xs" data-type="column"> <img class="" src="[tag_companion_uri]/sections/images/bw-logo-2.png"/></div> </div></div> <div class="col-xs-12 col-sm-3"><div class="card mdc-elevation--z3"> <div class="flexbox image-holder middle-sm center-xs" data-type="column"> <img class="" src="[tag_companion_uri]/sections/images/bw-logo-3.png"/></div> </div></div> <div class="col-xs-12 col-sm-3"><div class="card mdc-elevation--z3"> <div class="flexbox image-holder middle-sm center-xs" data-type="column"> <img class="" src="[tag_companion_uri]/sections/images/bw-logo-4.png"/></div> </div></div> </div></div> </div>',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-clients-2-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/clients-2-materialis.png?v=1551109271',
    'description' => 'Clients',
    'category' => 'clients',
    'prepend' => false,
    'pro' => false,
    'export' => 'module.exports={canAlignRowItemsContent:false}',
  ),
  7 => 
  array (
    'index' => 1024,
    'id' => 'contact-1',
    'elementId' => 'contact-1',
    'type' => 'section-available',
    'name' => 'Contact',
    'content' => '<div data-label="Contact" data-id="contact-1" data-export-id="contact-1" data-category="contact" class="contact-1 content-section content-section-spacing-large content-relative white-text" data-parallax-depth="20"><div class="gridContainer"> <div class="row text-center"><div class="section-title-col" data-type="column"> <h2>Contact us</h2> <p class="lead">With the Internet spreading linke wildfire and reaching every part of our daily life, more and more traffic is directed to websites in search for information.</p></div> </div> <div class="row text-center"> <div class="col-xs-12 col-sm-8 col-sm-offset-2 contact-form-wrapper inline-info"> <div class="card mdc-elevation--z3 col-padding-top"> <div class="dark-text" data-content-shortcode="materialis_contact_form" data-editable="true">[materialis_contact_form]</div></div> </div></div> </div></div>',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-contact-1.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/contact-1.png?v=1551109271',
    'description' => 'Contact',
    'category' => 'contact',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
  ),
  8 => 
  array (
    'index' => 1042,
    'id' => 'content-13-materialis',
    'elementId' => 'content-8',
    'type' => 'section-available',
    'name' => 'Content',
    'content' => '<div data-label="Content" data-id="content-13-materialis" data-export-id="content-13-materialis" data-category="content" class="content-13m content-section"><div> <div class="row middle-md middle-xs"><div class="col-md-6 col-xs-12 col-sm-6 bag-image mdc-elevation--z0" data-bg="image"></div> <div class="col-md-5 col-md-offset-1 col-xs-12 col-sm-6 content-left-sm full-col-right-padding first-xs last-sm col-padding" data-type="column"> <h6 class="upper">About us</h6> <h3>Protective Preventative Maintenance</h3> <p class="space-top-small">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.</p> <a href="#" class="button read-more link color1 negative-margin space-top-small">Read more</a></div> </div></div> </div>',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-content-13-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/content-13-materialis.png?v=1551109271',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro' => false,
    'export' => 'module.exports={canRevertColumnsOnMobile:true}',
  ),
  9 => 
  array (
    'index' => 1041,
    'id' => 'content-12-materialis',
    'elementId' => 'content-7',
    'type' => 'section-available',
    'name' => 'Content',
    'content' => '<div data-label="Content" data-id="content-12-materialis" data-export-id="content-12-materialis" data-category="content" class="content-12m content-section"><div> <div class="row middle-xs"><div class="col-md-5 col-xs-12 col-sm-6 content-left-sm full-col-left-padding col-padding" data-type="column"> <h6 class="upper">About us</h6> <h3>Protective Preventative Maintenance</h3> <p class="space-top-small">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.</p> <a href="#" class="button read-more link color1 negative-margin space-top-small">Read more</a></div> <div class="col-md-6 col-md-offset-1 col-xs-12 col-sm-6 bag-image mdc-elevation--z0" data-bg="image"></div></div> </div></div>',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-content-12-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/content-12-materialis.png?v=1551109271',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
  ),
  10 => 
  array (
    'index' => 1055,
    'id' => 'content-6',
    'elementId' => 'content-21',
    'type' => 'section-available',
    'name' => 'Content',
    'content' => '<div data-label="Content" data-id="content-6" data-export-id="content-6" data-category="content" class="content-6 content-section content-section-spacing-large"><div class="gridContainer"> <div class="row text-center"><div class="section-title-col" data-type="column"> <h2>This is one of the things we do best</h2> <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.</p></div> </div> <div class="row middle-sm"> <div class="col-xs-12 col-sm-6"> <div class="row"> <div class="col-xs-12 space-bottom" data-type="column"> <h3 class="color1">Lorem ipsum dolor sit amet.</h3> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer iaculis metus eget libero convallis, a sagittis elit commodo. Aliquam ultricies dui orci, id rutrum lectus pellentesque ut.</p></div> <div class="col-xs-12" data-type="row" data-max-items="4"><div class="row space-bottom"> <div class="col-xs-12 col-md-fit" data-fixed="true"><i class="mdi mdi-codepen icon bordered round color1"></i></div> <div class="col-xs-12 col-md" data-type="column"><h5 class="color1">FLEXIBLE CODE</h5> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></div> </div> <div class="row space-bottom"> <div class="col-xs-12 col-md-fit" data-fixed="true"> <i class="mdi mdi-plane-shield icon bordered round color1"></i></div> <div class="col-xs-12 col-md" data-type="column"><h5 class="color1">FLEXIBLE CODE</h5> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></div> </div> <div class="row space-bottom"> <div class="col-xs-12 col-md-fit" data-fixed="true"> <i class="mdi mdi-cube-outline icon bordered round color1"></i></div> <div class="col-xs-12 col-md" data-type="column"><h5 class="color1">FLEXIBLE CODE</h5> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></div> </div></div> </div></div> <div class="col-xs-12 col-sm-6 flexbox around-xs top-xs"><div class="overlay-box middle-xs center-xs flexbox box-image"> <div class="overlay-box-offset offset-border mdc-elevation--z5 border-color1 hide-xs border-radius-8 "></div> <img class="mdc-elevation--z10 rounded" src="[tag_companion_uri]/sections/images/content-5.jpg"/></div> </div></div> </div></div>',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-content-6.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/content-6.png?v=1551109271',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro' => false,
    'export' => 'modules.export={canAlignRowItemsContent:false,sectionStyle:{"nomedia":{".overlay-box .overlay-box-offset":{transform:"translate(10%, 10%)",width:"100%",height:"100%"}}}}',
  ),
  11 => 
  array (
    'index' => 1054,
    'id' => 'content-5-materialis',
    'elementId' => 'content-20',
    'type' => 'section-available',
    'name' => 'Content',
    'content' => '<div data-label="Content" data-id="content-5-materialis" data-export-id="content-5-materialis" data-category="content" class="content-5m content-section-spacing-large content-section"><div class="gridContainer"> <div class="row"><div class="col-xs-12 col-sm-8 col-sm-offset-2 space-bottom text-center col-padding-small-xs " data-type="column"> <img class="mdc-elevation--z13 rounded" src="[tag_companion_uri]/sections/images/image-5.jpg"></div> <div class="col-xs-12 text-center large" data-type="column"><h2 class="space-bottom">Guidelines For Inkjet Cartridge Refill</h2> <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.</p> <a class="button color1 big mdc-elevation--z3">GET STARTED</a></div> </div></div> </div>',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-content-5-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/content-5-materialis.png?v=1551109271',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro' => false,
    'export' => 'module.exports={canRevertColumnsOnMobile:true}',
  ),
  12 => 
  array (
    'index' => 1058,
    'id' => 'content-7-materialis',
    'elementId' => 'content-24',
    'type' => 'section-available',
    'name' => 'Content',
    'content' => '<div data-label="Content" data-id="content-7-materialis" data-export-id="content-7-materialis" data-category="content" class="content-7m content-section-spacing-large content-section"><div class="gridContainer"> <div class="row middle-sm"><div class="col-md-6 col-xs-12 col-sm-6 col-padding-small-xs"> <img class="mdc-elevation--z13 img-rounded" src="[tag_companion_uri]/sections/images/image-6.jpg"></div> <div class="col-md-5 col-md-offset-1 col-xs-12 col-sm-6 content-left-sm col-padding-small-xs" data-type="column"><h6 class="upper">Our story</h6> <h3 class="space-bottom">How To Meet That Special Someone</h3> <p class="space-top">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.</p> <a href="#" class="button read-more link color1 space-top negative-margin">Read more about us <i class="mdi mdi-arrow-right-thick read-more-icon"></i></a></div> </div></div> </div>',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-content-7-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/content-7-materialis.png?v=1551109271',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro' => false,
    'export' => 'module.exports={canRevertColumnsOnMobile:true}',
  ),
  13 => 
  array (
    'index' => 1059,
    'id' => 'content-8-materialis',
    'elementId' => 'content-25',
    'type' => 'section-available',
    'name' => 'Content',
    'content' => '<div data-label="Content" data-id="content-8-materialis" data-export-id="content-8-materialis" data-category="content" class="content-8m content-section-spacing-large content-section"><div class="gridContainer"> <div class="row middle-sm"><div class="col-md-5 col-xs-12 col-sm-6 space-bottom-xs" data-type="column"> <h6 class="upper">Our philosophy</h6> <h3>Protective Preventative Maintenance</h3> <p class="space-top">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.</p> <a href="#" class="button read-more link color1 space-top negative-margin">Read more <i class="mdi mdi-arrow-right-thick read-more-icon"></i></a> </div> <div class="col-md-6 col-md-offset-1 col-xs-12 col-sm-6"> <img class="mdc-elevation--z9 rounded" src="[tag_companion_uri]/sections/images/image-4.jpg"></div> </div></div> </div>',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-content-8-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/content-8-materialis.png?v=1551109271',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
  ),
  14 => 
  array (
    'index' => 1062,
    'id' => 'counters-1-materialis',
    'elementId' => 'counters-1',
    'type' => 'section-available',
    'name' => 'Counters',
    'content' => '<div data-label="Counters" data-id="counters-1-materialis" data-export-id="counters-1-materialis" data-category="counters" class="counters-1m content-section content-section-spacing-large"><div class="gridContainer"> <div class="row"><div class="section-title-col" data-type="column"> <h2>Counters</h2> <p class="lead">With the Internet spreading linke wildfire and reaching every part of our daily life, more and more traffic is directed to websites in search for information.</p></div> </div> <div class="row space-top content-center-sm cols-separator-between center-sm" data-type="row"> <div class="col-xs-12 col-sm-4 col-md-4 counter-box box-padding-lr-medium space-bottom"> <div class="row space-bottom-small"> <div class="col-sm-fit no-padding"> <i class="mdi mdi-leaf icon small bordered round color1"></i></div> <div class="col-sm-fit no-padding"><h2 class="counter-text font-300 color1" data-min="0" data-max="80" data-duration="2000" data-prefix="" data-suffix="+" data-countup="true"></h2></div> </div> <h6>predefined themes</h6></div> <div class="col-xs-12 col-sm-4 col-md-4 counter-box box-padding-lr-medium space-bottom"><div class="row space-bottom-small"> <div class="col-sm-fit no-padding"><i class="mdi mdi-emoticon icon small bordered round color1"></i></div> <div class="col-sm-fit no-padding"><h2 class="counter-text font-300 color1" data-min="0" data-max="80" data-duration="2000" data-prefix="" data-suffix="+" data-countup="true"></h2></div> </div> <h6>happy clients</h6></div> <div class="col-xs-12 col-sm-4 col-md-4 counter-box box-padding-lr-medium space-bottom"><div class="row space-bottom-small"> <div class="col-sm-fit no-padding"><i class="mdi mdi-trophy icon small bordered round color1"></i></div> <div class="col-sm-fit no-padding"><h2 class="counter-text font-300 color1" data-min="0" data-max="80" data-duration="2000" data-prefix="" data-suffix="+" data-countup="true"></h2></div> </div> <h6>awards won</h6></div> </div></div> </div>',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-counters-1-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/counters-1-materialis.png?v=1551109271',
    'description' => 'Counters',
    'category' => 'counters',
    'prepend' => false,
    'pro' => false,
    'export' => 'module.exports={customColor:[{colorClass:{selector:\'.counter-text\',prefix:\'\',suffix:\'\'}}]}',
  ),
  15 => 
  array (
    'index' => 1066,
    'id' => 'counters-2',
    'elementId' => 'counters-5',
    'type' => 'section-available',
    'name' => 'Counters',
    'content' => '<div data-label="Counters" data-id="counters-2" data-export-id="counters-2" data-category="counters" class="counters-2 content-section content-section-spacing-large"><div class="gridContainer"> <div class="row text-center"><div class="section-title-col" data-type="column"> <h2>Counters</h2> <p class="lead">With the Internet spreading linke wildfire and reaching every part of our daily life, more and more traffic is directed to websites in search for information.</p></div> </div> <div class="row content-center-sm center-sm" data-type="row"> <div class="col-xs-12 col-sm-4 space-bottom"> <i class="mdi mdi-leaf icon color1"></i> <h3 class="counter-text font-400 color-black" data-min="0" data-max="80" data-duration="2000" data-prefix="" data-suffix="+" data-countup="true"></h3> <h5 class="upper color2">predefined themes</h5></div> <div class="col-xs-12 col-sm-4 space-bottom"><i class="mdi mdi-emoticon icon color1"></i> <h3 class="counter-text font-400 color-black" data-min="10000" data-max="15000" data-duration="2000" data-prefix="" data-suffix="+" data-countup="true"></h3> <h5 class="upper color2">happy clients</h5></div> <div class="col-xs-12 col-sm-4 space-bottom"><i class="mdi mdi-trophy icon color1 "></i> <h3 class="counter-text font-400 color-black" data-min="0" data-max="25" data-duration="2000" data-prefix="" data-suffix="+" data-countup="true"></h3> <h5 class="upper color2">awards won</h5></div> </div></div> </div>',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-counters-2.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/counters-2.png?v=1551109271',
    'description' => 'Counters',
    'category' => 'counters',
    'prepend' => false,
    'pro' => false,
    'export' => 'module.exports={customColor:[{colorClass:{selector:\'.counter-text\',prefix:\'\',suffix:\'\'}}]}',
  ),
  16 => 
  array (
    'index' => 1067,
    'id' => 'counters-2-materialis',
    'elementId' => 'counters-6',
    'type' => 'section-available',
    'name' => 'Counters',
    'content' => '<div data-label="Counters" data-id="counters-2-materialis" data-export-id="counters-2-materialis" data-category="counters" class="counters-2m content-section content-section-spacing-large"><div class="gridContainer"> <div class="row"><div class="section-title-col" data-type="column"> <h2>Counters</h2> <p class="lead">With the Internet spreading linke wildfire and reaching every part of our daily life, more and more traffic is directed to websites in search for information.</p></div> </div> <div class="row spaced-cols center-sm" data-type="row" data-fixed="true"> <div class="col-xs-12 col-sm-4 space-bottom-small col-padding-xs"> <div class="circle-counter color1"> <svg class="circle-svg" viewBox="0 0 100 100"> <circle r="48" stroke-linecap="round" cx="50" cy="50" fill="transparent" stroke-dasharray="301.6" stroke-dashoffset="301.6px"></circle> <circle class="circle-bar" r="48" stroke-linecap="round" cx="50" cy="50" fill="transparent" stroke-dasharray="301.6" stroke-dashoffset="301.6px"></circle></svg> <div class="circle-content"><h2 class="font-100" data-min="0" data-max="100" data-stop="50" data-prefix="" data-suffix="%" data-countup="true"></h2> <p class="font-500 color1">Design</p></div> </div></div> <div class="col-xs-12 col-sm-4 space-bottom-small col-padding-xs"><div class="circle-counter color2"> <svg class="circle-svg" viewBox="0 0 100 100"><circle r="48" stroke-linecap="round" cx="50" cy="50" fill="transparent" stroke-dasharray="301.6" stroke-dashoffset="301.6px"></circle> <circle class="circle-bar" r="48" stroke-linecap="round" cx="50" cy="50" fill="transparent" stroke-dasharray="301.6" stroke-dashoffset="301.6px"></circle></svg> <div class="circle-content"><h2 class="font-100" data-min="0" data-max="100" data-stop="75" data-prefix="" data-suffix="%" data-countup="true"></h2> <p class="font-500 color2">Development</p></div> </div></div> <div class="col-xs-12 col-sm-4 space-bottom-small col-padding-xs"><div class="circle-counter color4"> <svg class="circle-svg" viewBox="0 0 100 100"><circle r="48" stroke-linecap="round" cx="50" cy="50" fill="transparent" stroke-dasharray="301.6" stroke-dashoffset="301.6px"></circle> <circle class="circle-bar" r="48" stroke-linecap="round" cx="50" cy="50" fill="transparent" stroke-dasharray="301.6" stroke-dashoffset="301.6px"></circle></svg> <div class="circle-content"><h2 class="font-100" data-min="0" data-max="100" data-stop="90" data-prefix="" data-suffix="%" data-countup="true"></h2> <p class="font-500 color4">SEO Expertize</p></div> </div></div> </div></div> </div>',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-counters-2-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/counters-2-materialis.png?v=1551109271',
    'description' => 'Counters',
    'category' => 'counters',
    'prepend' => false,
    'pro' => false,
    'export' => 'module.exports={canAlignRowItemsContent:false,customColor:[{colorClass:{selector:\'.circle-counter\',prefix:\'\',suffix:\'\'}},{colorClass:{selector:\'.circle-counter p\',prefix:\'\',suffix:\'\'}}]}',
  ),
  17 => 
  array (
    'index' => 1071,
    'id' => 'cta-1-materialis',
    'elementId' => 'cta-1',
    'type' => 'section-available',
    'name' => 'Cta',
    'content' => '<div data-label="Cta" data-id="cta-1-materialis" data-export-id="cta-1-materialis" data-category="cta" class="content-relative content-section content-section-spacing-large cta-1-materialis section-title-col-white-text" data-section-ov="1" data-parallax-depth="20"><div class="gridContainer"> <div class="row text-center col-sm-padding-medium"><div class="col-md-6 col-md-offset-3 col-xs-10 col-xs-offset-1 card mdc-elevation--z3 box-padding-lr-small"> <div data-type="column" class=""><h2 class="">Download now</h2> <p class="">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.</p> <a class="button big color1 mdc-elevation--z1 mdc-ripple-upgraded">START NOW</a></div> </div></div> </div></div>',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-cta-1-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/cta-1-materialis.png?v=1551109271',
    'description' => 'Cta',
    'category' => 'cta',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
  ),
  18 => 
  array (
    'index' => 1077,
    'id' => 'cta-blue-section',
    'elementId' => 'cta-7',
    'type' => 'section-available',
    'name' => 'Cta',
    'content' => '<div data-label="Cta" data-id="cta-blue-section" data-export-id="cta-blue-section" data-category="cta" class="cta-blue-section content-section content-section-spacing-large bg-color1 white-text"><div class="gridContainer"> <div class="row middle-xs"><div class="col-xs-12 col-sm-7 col-md-8 space-bottom-xs" data-type="column"> <h2><b>Join us!</b> <span class="font-300">It will only take a minute</span></h2> </div> <div class="col-xs-12 col-sm-5 col-md-4" data-type="column"> <a class="button color2 big" href="#">GET STARTED TODAY</a></div> </div></div> </div>',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-cta-blue-section.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/cta-blue-section.png?v=1551109271',
    'description' => 'Cta',
    'category' => 'cta',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
  ),
  19 => 
  array (
    'index' => 1080,
    'id' => 'features-1-materialis',
    'elementId' => 'features-1',
    'type' => 'section-available',
    'name' => 'Features',
    'content' => '<div data-label="Features" data-id="features-1-materialis" data-export-id="features-1-materialis" data-category="features" class="features-1m content-section content-section-spacing-large"><div class="gridContainer"> <div class="row text-center"><div class="section-title-col" data-type="column"> <h2>The Main Features</h2> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.</p></div> </div> <div class="row top-xs space-top-small content-center-sm" data-type="row"> <div class="col-md-4 col-sm-4 col-xs-12 space-bottom" data-type="column"> <i class="mdi icon mdi-database big round reverse color1"></i> <h4>Popular Uses Of The Internet</h4> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></div> <div class="col-md-4 col-sm-4 col-xs-12 space-bottom" data-type="column"><i class="mdi icon mdi-database big round reverse color1"></i> <h4>Make Myspace Your Best</h4> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></div> <div class="col-md-4 col-sm-4 col-xs-12 space-bottom" data-type="column"><i class="mdi icon mdi-database big round reverse color1"></i> <h4>E Banks That Accept Us</h4> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></div> </div></div> </div>',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-features-1-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/features-1-materialis.png?v=1551109271',
    'description' => 'Features',
    'category' => 'features',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
  ),
  20 => 
  array (
    'index' => 1081,
    'id' => 'features-10-materialis',
    'elementId' => 'features-2',
    'type' => 'section-available',
    'name' => 'Features',
    'content' => '<div data-label="Features" data-id="features-10-materialis" data-export-id="features-10-materialis" data-category="features" class="features-10m content-section-spacing-large content-section"><div class="gridContainer"> <div class="row"><div class="section-title-col" data-type="column"> <h2>The Main Features</h2> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.</p></div> </div> <div class="row "> <div class="col-xs-12 col-md-10 col-md-offset-1"> <div class="row space-top spaced-cols content-center-sm" data-type="row" data-max-items="4"> <div class="col-xs-10 col-md-4 col-sm-6 col-sm-offset-0 col-xs-offset-1"> <div class="card no-radius mdc-elevation--z1 y-move bg-color-white padding-24 bordered" data-type="column"> <i class="mdi icon mdi-database big round reverse color1"></i> <h6>Popular Uses Of The Internet</h6></div> </div> <div class="col-xs-10 col-md-4 col-sm-6 col-sm-offset-0 col-xs-offset-1"> <div class="card no-radius mdc-elevation--z1 y-move bg-color-white padding-24 bordered" data-type="column"> <i class="mdi icon mdi-database big round reverse color1"></i> <h6>How To Meet That Special</h6></div> </div> <div class="col-xs-10 col-md-4 col-sm-6 col-sm-offset-0 col-xs-offset-1"> <div class="card no-radius mdc-elevation--z1 y-move bg-color-white padding-24 bordered" data-type="column"> <i class="mdi icon mdi-database big round reverse color1"></i> <h6>Make Myspace Your Best</h6></div> </div> <div class="col-xs-10 col-md-4 col-sm-6 col-sm-offset-0 col-xs-offset-1"> <div class="card no-radius mdc-elevation--z1 y-move bg-color-white padding-24 bordered" data-type="column"> <i class="mdi icon mdi-database big round reverse color1"></i> <h6>Make Myspace Your Best</h6></div> </div> <div class="col-md-4 col-sm-6 col-sm-offset-0 col-xs-10 col-xs-offset-1"> <div class="card no-radius mdc-elevation--z1 y-move bg-color-white padding-24 bordered" data-type="column"> <i class="mdi icon mdi-database big round reverse color1"></i> <h6>Make Myspace Your Best</h6></div> </div> <div class="col-md-4 col-sm-6 col-sm-offset-0 col-xs-10 col-xs-offset-1"> <div class="card no-radius mdc-elevation--z1 y-move bg-color-white padding-24 bordered" data-type="column"> <i class="mdi icon mdi-database big round reverse color1"></i> <h6>Make Myspace Your Best</h6></div> </div></div> </div></div> </div></div>',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-features-10-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/features-10-materialis.png?v=1551109271',
    'description' => 'Features',
    'category' => 'features',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
  ),
  21 => 
  array (
    'index' => 1082,
    'id' => 'features-12',
    'elementId' => 'features-3',
    'type' => 'section-available',
    'name' => 'Features',
    'content' => '<div data-label="Features" data-id="features-12" data-export-id="features-12" data-category="features" class="features-12 content-section content-section-spacing-large "><div class="gridContainer"> <div class="row text-center"><div class="section-title-col" data-type="column"> <h2>A few things we’re great at</h2> <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.Ut enim ad minim veniam, quis nostrud exercitation.</p></div> </div> <div class="row spaced-cols" data-type="row"> <div class="col-xs-12 col-sm-6"> <div class="row"> <div class="col-xs-12 col-sm-fit icon-column no-padding" data-fixed="true"> <i class="mdi icon mdi-matrix round bordered color1"></i> </div> <div class="col-xs-12 col-sm" data-type="column"> <h5 class="color1">FLEXIBLE CODE</h5> <p class="">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p></div> </div></div> <div class="col-xs-12 col-sm-6"><div class="row"> <div class="col-xs-12 col-sm-fit icon-column no-padding" data-fixed="true"><i class="mdi icon mdi-codepen round bordered color1"></i></div> <div class="col-xs-12 col-sm" data-type="column"><h5 class="color1">FLEXIBLE CODE</h5> <p class="">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p></div> </div></div> <div class="col-xs-12 col-sm-6"><div class="row"> <div class="col-xs-12 col-sm-fit icon-column no-padding" data-fixed="true"><i class="mdi icon mdi-cube round bordered color1"></i></div> <div class="col-xs-12 col-sm" data-type="column"><h5 class="color1">FLEXIBLE CODE</h5> <p class="">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p></div> </div></div> <div class="col-xs-12 col-sm-6"><div class="row"> <div class="col-xs-12 col-sm-fit icon-column no-padding" data-fixed="true"><i class="mdi icon mdi-database round bordered color1"></i></div> <div class="col-xs-12 col-sm" data-type="column"><h5 class="color1">FLEXIBLE CODE</h5> <p class="">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p></div> </div></div> </div></div> </div>',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-features-12.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/features-12.png?v=1551109271',
    'description' => 'Features',
    'category' => 'features',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
  ),
  22 => 
  array (
    'index' => 1083,
    'id' => 'features-12-card-bordered',
    'elementId' => 'features-4',
    'type' => 'section-available',
    'name' => 'Features',
    'content' => '<div data-label="Features" data-id="features-12-card-bordered" data-export-id="features-12-card-bordered" data-category="features" class="features-12-card-bordered content-section content-section-spacing-large"><div class="gridContainer"> <div class="row text-center"><div class="section-title-col" data-type="column"> <h2>A few things we’re great at</h2> <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.Ut enim ad minim veniam, quis nostrud exercitation.</p></div> </div> <div class="row spaced-cols" data-type="row"> <div class="col-xs-12 col-sm-6"> <div class="card mdc-elevation--z3 row-card bordered y-move"> <div class="row"> <div class="col-xs-12 col-sm-fit icon-column" data-fixed="true"> <i class="mdi icon mdi-matrix round bordered color1"></i> </div> <div class="col-xs-12 col-sm" data-type="column"> <h5 class="color1">FLEXIBLE CODE</h5> <p class="">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p></div> </div></div> </div> <div class="col-xs-12 col-sm-6"> <div class="card mdc-elevation--z3 row-card bordered y-move"> <div class="row"> <div class="col-xs-12 col-sm-fit icon-column" data-fixed="true"> <i class="mdi icon mdi-codepen round bordered color1"></i> </div> <div class="col-xs-12 col-sm" data-type="column"> <h5 class="color1">FLEXIBLE CODE</h5> <p class="">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p></div> </div></div> </div> <div class="col-xs-12 col-sm-6"> <div class="card mdc-elevation--z3 row-card bordered y-move"> <div class="row"> <div class="col-xs-12 col-sm-fit icon-column" data-fixed="true"> <i class="mdi icon mdi-cube round bordered color1"></i> </div> <div class="col-xs-12 col-sm" data-type="column"> <h5 class="color1">FLEXIBLE CODE</h5> <p class="">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p></div> </div></div> </div> <div class="col-xs-12 col-sm-6"> <div class="card mdc-elevation--z3 row-card bordered y-move"> <div class="row"> <div class="col-xs-12 col-sm-fit icon-column" data-fixed="true"> <i class="mdi icon mdi-database round bordered color1"></i> </div> <div class="col-xs-12 col-sm" data-type="column"> <h5 class="color1">FLEXIBLE CODE</h5> <p class="">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p></div> </div></div> </div></div> </div></div>',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-features-12-card-bordered.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/features-12-card-bordered.png?v=1551109271',
    'description' => 'Features',
    'category' => 'features',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
  ),
  23 => 
  array (
    'index' => 1084,
    'id' => 'features-13',
    'elementId' => 'features-5',
    'type' => 'section-available',
    'name' => 'Features',
    'content' => '<div data-label="Features" data-id="features-13" data-export-id="features-13" data-category="features" class="features-13 content-section content-section-spacing-large"><div class="gridContainer"> <div class="row text-center"><div class="section-title-col" data-type="column"> <h2>A few things we’re great at</h2> <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.Ut enim ad minim veniam, quis nostrud exercitation.</p></div> </div> <div class="row spaced-cols" data-type="row"> <div class="col-xs-12 col-sm-6 col-md-3 space-bottom"> <i class="mdi icon mdi-matrix big round bordered color1"></i> <h4>FLEXIBLE CODE</h4> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p> <a class="button small y-move color1" href="#">GET STARTED</a></div> <div class="col-xs-12 col-sm-6 col-md-3 space-bottom"><i class="mdi icon mdi-matrix big round bordered color1"></i> <h4>FLEXIBLE CODE</h4> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p> <a class="button small y-move color1" href="#">GET STARTED</a></div> <div class="col-xs-12 col-sm-6 col-md-3 space-bottom"><i class="mdi icon mdi-matrix big round bordered color1"></i> <h4>FLEXIBLE CODE</h4> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p> <a class="button small y-move color1" href="#">GET STARTED</a></div> <div class="col-xs-12 col-sm-6 col-md-3 space-bottom"><i class="mdi icon mdi-codepen big round bordered color1"></i> <h4>FLEXIBLE CODE</h4> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p> <a class="button small y-move color1" href="#">GET STARTED</a></div> </div></div> </div>',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-features-13.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/features-13.png?v=1551109271',
    'description' => 'Features',
    'category' => 'features',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
  ),
  24 => 
  array (
    'index' => 1085,
    'id' => 'features-13-card-bordered',
    'elementId' => 'features-6',
    'type' => 'section-available',
    'name' => 'Features',
    'content' => '<div data-label="Features" data-id="features-13-card-bordered" data-export-id="features-13-card-bordered" data-category="features" class="features-13 content-section content-section-spacing-large"><div class="gridContainer"> <div class="row text-center"><div class="section-title-col" data-type="column"> <h2>A few things we’re great at</h2> <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.Ut enim ad minim veniam, quis nostrud exercitation.</p></div> </div> <div class="row spaced-cols content-center-sm" data-type="row"> <div class="col-xs-12 col-sm-4"> <div class="card mdc-elevation--z3 bordered y-move" data-type="column"> <i class="mdi icon mdi-codepen big round reverse color1"></i> <h4>FLEXIBLE CODE</h4> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p> <a class="button small y-move color1" href="#">GET STARTED</a></div> </div> <div class="col-xs-12 col-sm-4"> <div class="card mdc-elevation--z3 bordered y-move" data-type="column"> <i class="mdi icon mdi-codepen big round reverse color1"></i> <h4>FLEXIBLE CODE</h4> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p> <a class="button small y-move color1" href="#">GET STARTED</a></div> </div> <div class="col-xs-12 col-sm-4"> <div class="card mdc-elevation--z3 bordered y-move" data-type="column"> <i class="mdi icon mdi-codepen big round reverse color1"></i> <h4>FLEXIBLE CODE</h4> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p> <a class="button small y-move color1" href="#">GET STARTED</a></div> </div></div> </div></div>',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-features-13-card-bordered.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/features-13-card-bordered.png?v=1551109271',
    'description' => 'Features',
    'category' => 'features',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
  ),
  25 => 
  array (
    'index' => 1088,
    'id' => 'features-16',
    'elementId' => 'features-9',
    'type' => 'section-available',
    'name' => 'Features',
    'content' => '<div data-label="Features" data-id="features-16" data-export-id="features-16" data-category="features" class="features-16 content-section content-section-spacing-large"><div class="gridContainer"> <div class="row text-center"><div class="section-title-col" data-type="column"> <h2>A few things we’re great at</h2> <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation. Ut enim ad minim veniam, quis nostrud exercitation.</p></div> </div> <div class="row spaced-cols" data-type="row"> <div class="col-xs-12 col-sm-6 col-md-4 space-bottom"> <img class="face mdc-elevation--z3" src="[tag_companion_uri]/sections/images/computer-2569652.jpg"> <div data-type="column" class=" col-padding-small col-padding-small-xs description-container"> <h4 class="font-500">Responsive design</h4> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p> <a class="read-more">learn more</a></div> </div> <div class="col-xs-12 col-sm-6 col-md-4 space-bottom"> <img class="face mdc-elevation--z3" src="[tag_companion_uri]/sections/images/apple-1838564.jpg"> <div data-type="column" class=" col-padding-small col-padding-small-xs description-container"> <h4 class="font-500">Responsive design</h4> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p> <a class="read-more">learn more</a></div> </div> <div class="col-xs-12 col-sm-6 col-md-4 space-bottom"> <img class="face mdc-elevation--z3" src="[tag_companion_uri]/sections/images/laptop-2559795.jpg"> <div data-type="column" class=" col-padding-small col-padding-small-xs description-container"> <h4 class="font-500">Responsive design</h4> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p> <a class="read-more">learn more</a></div> </div></div> </div></div>',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-features-16.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/features-16.png?v=1551109271',
    'description' => 'Features',
    'category' => 'features',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
  ),
  26 => 
  array (
    'index' => 1089,
    'id' => 'features-16-card-bordered',
    'elementId' => 'features-10',
    'type' => 'section-available',
    'name' => 'Features',
    'content' => '<div data-label="Features" data-id="features-16-card-bordered" data-export-id="features-16-card-bordered" data-category="features" class="features-16-card-bordered content-section content-section-spacing-large"><div class="gridContainer"> <div class="row text-center"><div class="section-title-col" data-type="column"> <h2>A few things we’re great at</h2> <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.Ut enim ad minim veniam, quis nostrud exercitation.</p></div> </div> <div class="row spaced-cols" data-type="row" data-max-items="4"> <div class="col-xs-12 col-sm-6 col-md-4"> <div class="card mdc-elevation--z3 no-padding y-move"> <img class="face" src="[tag_companion_uri]/sections/images/computer-2569652.jpg"> <div data-type="column" class=" col-padding-small col-padding-small-xs description-container"> <h4 class="font-500">Responsive Design</h4> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p></div> <div data-type="column" class=" col-padding-small col-padding-small-xs read-more-container"><a class="read-more">learn more</a></div> </div></div> <div class="col-xs-12 col-sm-6 col-md-4"><div class="card mdc-elevation--z3 no-padding y-move"> <img class="face" src="[tag_companion_uri]/sections/images/apple-1838564.jpg"> <div data-type="column" class=" col-padding-small col-padding-small-xs description-container"> <h4 class="font-500">Responsive Design</h4> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p></div> <div data-type="column" class=" col-padding-small col-padding-small-xs read-more-container"><a class="read-more">learn more</a></div> </div></div> <div class="col-xs-12 col-sm-6 col-md-4"><div class="card mdc-elevation--z3 no-padding y-move"> <img class="face" src="[tag_companion_uri]/sections/images/laptop-2559795.jpg"> <div data-type="column" class=" col-padding-small col-padding-small-xs description-container"> <h4 class="font-500">Responsive Design</h4> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p></div> <div data-type="column" class=" col-padding-small col-padding-small-xs read-more-container"><a class="read-more">learn more</a></div> </div></div> </div></div> </div>',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-features-16-card-bordered.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/features-16-card-bordered.png?v=1551109271',
    'description' => 'Features',
    'category' => 'features',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
  ),
  27 => 
  array (
    'index' => 1100,
    'id' => 'latest-news-1-materialis',
    'elementId' => 'latest-news-1',
    'type' => 'section-available',
    'name' => 'Latest-news',
    'content' => '<div data-label="Latest-news" data-id="latest-news-1-materialis" data-export-id="latest-news-1-materialis" data-category="latest_news" class="latest-news-1-materialis content-section content-section-spacing-large"><div class="gridContainer"> <div class="row"><div data-type="column" class="section-title-col"> <h2>Latest News</h2> <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p></div> </div> <div class="row content-left-sm"> <div data-type="row" data-dynamic-columns="handled" data-content-shortcode="materialis_latest_news" data-max-items="4">[materialis_latest_news]</div></div> <div class="row"><div class="col-xs-12 text-center"> <a class="button big color1 mdc-elevation--z3" data-attr-shortcode="href:materialis_blog_link" href="[materialis_blog_link]">VISIT OUR BLOG</a></div> </div></div></div>',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-latest-news-1-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/latest-news-1-materialis.png?v=1551109271',
    'description' => 'Latest-news',
    'category' => 'latest_news',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
  ),
  28 => 
  array (
    'index' => 1106,
    'id' => 'overlappable-14-materialis',
    'elementId' => 'overlappable-3',
    'type' => 'section-available',
    'name' => 'Overlappable',
    'content' => '<div data-label="Overlappable" data-id="overlappable-14-materialis" data-export-id="overlappable-14-materialis" data-category="overlappable" class="overlappable-14-materialis content-section content-section-spacing-large" data-overlap="true"><div class="gridContainer"> <div data-type="row" class="row spaced-cols"><div class="col-xs-12 col-sm-4 content-on-center"> <div class="card no-radius mdc-elevation--z3 bg-color4" data-type="column"><h2 class="color-white no-margin-bottom font-400" data-fixed="true">10.5%</h2> <h6 class="color-white">PRINT</h6></div> </div> <div class="col-xs-12 col-sm-4 content-on-center"> <div class="card no-radius mdc-elevation--z3 bg-color3" data-type="column"> <h2 class="color-white no-margin-bottom font-400" data-fixed="true">50%</h2> <h6 class="color-white">DESIGN</h6></div> </div> <div class="col-xs-12 col-sm-4 content-on-center"> <div class="card no-radius mdc-elevation--z3 bg-color5" data-type="column"> <h2 class="color-white no-margin-bottom font-400" data-fixed="true">$10</h2> <h6 class="color-white">PROGRAMMING</h6></div> </div></div> </div></div>',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-overlappable-14-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/overlappable-14-materialis.png?v=1551109271',
    'description' => 'Overlappable',
    'category' => 'overlappable',
    'prepend' => true,
    'pro' => false,
    'export' => 'module.exports={allowSectionTitleOptions:false,afterInsert:function(){CP_Customizer.setMod(\'header_overlap_with\',\'50px\')},customColor:[{colorClass:{selector:\'div[class*="bg-"]\',prefix:\'bg-\',suffix:\'\'}}]}',
  ),
  29 => 
  array (
    'index' => 1109,
    'id' => 'overlappable-4',
    'elementId' => 'overlappable-6',
    'type' => 'section-available',
    'name' => 'Overlappable',
    'content' => '<div data-label="Overlappable" data-id="overlappable-4" data-export-id="overlappable-4" data-category="overlappable" class="overlappable-4 content-section content-section-spacing-large" data-overlap="true"><div class="gridContainer"> <div data-type="row" class="row spaced-cols text-center"><div class="col-xs-12 col-sm-4 "> <i class="mdi icon mdi-responsive large round aligncenter reverse color1"></i> <div data-type="column"> <h5>RESPONSIVE DESIGN</h5> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></div> </div> <div class="col-xs-12 col-sm-4 "> <i class="mdi icon mdi-settings large round aligncenter reverse color1"></i> <div data-type="column"><h5>SUPER FEATURES</h5> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></div> </div> <div class="col-xs-12 col-sm-4 "> <i class="mdi icon mdi-auto-fix large round aligncenter reverse color1"></i> <div data-type="column"><h5>DRAG AND DROP</h5> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></div> </div></div> </div></div>',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-overlappable-4.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/overlappable-4.png?v=1551109271',
    'description' => 'Overlappable',
    'category' => 'overlappable',
    'prepend' => true,
    'pro' => false,
    'export' => 'module.exports={allowSectionTitleOptions:false,afterInsert:function(){CP_Customizer.setMod(\'header_overlap_with\',\'56px\')}}',
  ),
  30 => 
  array (
    'index' => 1111,
    'id' => 'overlappable-5-materialis',
    'elementId' => 'overlappable-8',
    'type' => 'section-available',
    'name' => 'Overlappable',
    'content' => '<div data-label="Overlappable" data-id="overlappable-5-materialis" data-export-id="overlappable-5-materialis" data-category="overlappable" class="overlappable-5-materialis content-section content-section-spacing-large" data-overlap="true"><div class="gridContainer"> <div data-type="row" class="row spaced-cols "><div class="col-xs-12 col-sm-6 col-md-4 "> <div class="card mdc-elevation--z3 row-card"><div class="row"> <div class="col-xs-12 col-sm-fit icon-col" data-fixed="true"><i class="color1 icon mdi mdi-responsive reverse round big"></i></div> <div class="col-xs-12 col-sm" data-type="column"><h4 class="color-black">RESPONSIVE DESIGN</h4> <p class="">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></div> </div></div> </div> <div class="col-xs-12 col-sm-6 col-md-4 "> <div class="card mdc-elevation--z3 row-card"> <div class="row"> <div class="col-xs-12 col-sm-fit icon-col" data-fixed="true"> <i class="color1 icon mdi mdi-vector-square reverse round big"></i></div> <div class="col-xs-12 col-sm" data-type="column"><h4 class="color-black">SUPER FEATURES</h4> <p class="">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></div> </div></div> </div> <div class="col-xs-12 col-sm-6 col-md-4 "> <div class="card mdc-elevation--z3 row-card"> <div class="row"> <div class="col-xs-12 col-sm-fit icon-col" data-fixed="true"> <i class="color1 icon mdi mdi-arrange-bring-forward reverse round big"></i></div> <div class="col-xs-12 col-sm" data-type="column"><h4 class="color-black">DRAG AND DROP</h4> <p class="">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></div> </div></div> </div></div> </div></div>',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-overlappable-5-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/overlappable-5-materialis.png?v=1551109271',
    'description' => 'Overlappable',
    'category' => 'overlappable',
    'prepend' => true,
    'pro' => false,
    'export' => 'module.exports={allowSectionTitleOptions:false,afterInsert:function(){CP_Customizer.setMod(\'header_overlap_with\',\'95px\')}}',
  ),
  31 => 
  array (
    'index' => 1114,
    'id' => 'portfolio-1-materialis',
    'elementId' => 'portfolio-2',
    'type' => 'section-available',
    'name' => 'Portfolio',
    'content' => '<div data-label="Portfolio" data-id="portfolio-1-materialis" data-export-id="portfolio-1-materialis" data-category="portfolio" class="portfolio-1m content-section"><div> <div class="row text-center" data-type="row" data-fixed="true"><div class="col-md-4 col-sm-6 col-xs-12 no-gutter-col"> <div class="contentswap-effect " data-hover-fx="portfolio-1"><div class="initial-image"> <img data-size="600x354" src="[tag_companion_uri]/sections/images/image-1.png"></div> <div class="overlay bg-color-black"></div> <div class="swap-inner col-xs-12"> <div class="row full-height-row middle-xs"> <div class="col-xs-12 text-center white-text"> <h4 class="font-500">Project Name</h4> <a class="button color-white" href="#">View project</a></div> </div></div> </div></div> <div class="col-md-4 col-sm-6 col-xs-12 no-gutter-col"><div class="contentswap-effect " data-hover-fx="portfolio-1"> <div class="initial-image"> <img data-size="600x354" src="[tag_companion_uri]/sections/images/image-2.png"></div> <div class="overlay bg-color-black"></div> <div class="swap-inner col-xs-12"> <div class="row full-height-row middle-xs"> <div class="col-xs-12 text-center white-text"> <h4 class="font-500">Project Name</h4> <a class="button color-white" href="#">View project</a></div> </div></div> </div></div> <div class="col-md-4 col-sm-6 col-xs-12 no-gutter-col"><div class="contentswap-effect " data-hover-fx="portfolio-1"> <div class="initial-image"> <img data-size="600x354" src="[tag_companion_uri]/sections/images/image-3.png"></div> <div class="overlay bg-color-black"></div> <div class="swap-inner col-xs-12"> <div class="row full-height-row middle-xs"> <div class="col-xs-12 text-center white-text"> <h4 class="font-500">Project Name</h4> <a class="button color-white" href="#">View project</a></div> </div></div> </div></div> <div class="col-md-4 col-sm-6 col-xs-12 no-gutter-col"><div class="contentswap-effect " data-hover-fx="portfolio-1"> <div class="initial-image"> <img data-size="600x354" src="[tag_companion_uri]/sections/images/image-4.png"></div> <div class="overlay bg-color-black"></div> <div class="swap-inner col-xs-12"> <div class="row full-height-row middle-xs"> <div class="col-xs-12 text-center white-text"> <h4 class="font-500">Project Name</h4> <a class="button color-white" href="#">View project</a></div> </div></div> </div></div> <div class="col-md-4 col-sm-6 col-xs-12 no-gutter-col"><div class="contentswap-effect " data-hover-fx="portfolio-1"> <div class="initial-image"> <img data-size="600x354" src="[tag_companion_uri]/sections/images/image-5.png"></div> <div class="overlay bg-color-black"></div> <div class="swap-inner col-xs-12"> <div class="row full-height-row middle-xs"> <div class="col-xs-12 text-center white-text"> <h4 class="font-500">Project Name</h4> <a class="button color-white" href="#">View project</a></div> </div></div> </div></div> <div class="col-md-4 col-sm-6 col-xs-12 no-gutter-col"><div class="contentswap-effect " data-hover-fx="portfolio-1"> <div class="initial-image"> <img data-size="600x354" src="[tag_companion_uri]/sections/images/image-7.png"></div> <div class="overlay bg-color-black"></div> <div class="swap-inner col-xs-12"> <div class="row full-height-row middle-xs"> <div class="col-xs-12 text-center white-text"> <h4 class="font-500">Project Name</h4> <a class="button color-white" href="#">View project</a></div> </div></div> </div></div> <div class="col-md-4 col-sm-6 col-xs-12 no-gutter-col"><div class="contentswap-effect " data-hover-fx="portfolio-1"> <div class="initial-image"> <img data-size="600x354" src="[tag_companion_uri]/sections/images/image-6.png"></div> <div class="overlay bg-color-black"></div> <div class="swap-inner col-xs-12"> <div class="row full-height-row middle-xs"> <div class="col-xs-12 text-center white-text"> <h4 class="font-500">Project Name</h4> <a class="button color-white" href="#">View project</a></div> </div></div> </div></div> <div class="col-md-4 col-sm-6 col-xs-12 no-gutter-col"><div class="contentswap-effect " data-hover-fx="portfolio-1"> <div class="initial-image"> <img data-size="600x354" src="[tag_companion_uri]/sections/images/image-1.png"></div> <div class="overlay bg-color-black"></div> <div class="swap-inner col-xs-12"> <div class="row full-height-row middle-xs"> <div class="col-xs-12 text-center white-text"> <h4 class="font-500">Project Name</h4> <a class="button color-white" href="#">View project</a></div> </div></div> </div></div> <div class="col-md-4 col-sm-6 col-xs-12 no-gutter-col"><div class="contentswap-effect " data-hover-fx="portfolio-1"> <div class="initial-image"> <img data-size="600x354" src="[tag_companion_uri]/sections/images/image-4.png"></div> <div class="overlay bg-color-black"></div> <div class="swap-inner col-xs-12"> <div class="row full-height-row middle-xs"> <div class="col-xs-12 text-center white-text"> <h4 class="font-500">Project Name</h4> <a class="button color-white" href="#">View project</a></div> </div></div> </div></div> </div></div> </div>',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-portfolio-1-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/portfolio-1-materialis.png?v=1551109271',
    'description' => 'Portfolio',
    'category' => 'portfolio',
    'prepend' => false,
    'pro' => false,
    'export' => 'module.exports={canAlignRowItemsContent:false,customColor:[{colorClass:{selector:\'.overlay\',prefix:\'bg-\',suffix:\'\'}}]}',
  ),
  32 => 
  array (
    'index' => 1115,
    'id' => 'portfolio-2-materialis',
    'elementId' => 'portfolio-3',
    'type' => 'section-available',
    'name' => 'Portfolio',
    'content' => '<div data-label="Portfolio" data-id="portfolio-2-materialis" data-export-id="portfolio-2-materialis" data-category="portfolio" class="portfolio-2-materialis content-section-spacing-large content-section bg-color-white"><div class="gridContainer"> <div class="row"><div class="section-title-col" data-type="column"> <h2>Portfolio</h2> <p class="lead">With the Internet spreading linke wildfire and reaching every part of our daily life, more and more traffic is directed to websites in search for information.</p></div> </div> <div class="row text-left spaced-cols" data-type="row" data-fixed="true"> <div class="col-md-4 col-sm-6 col-xs-12"> <div class="card mdc-elevation--z3 no-padding " data-hover-fx="portfolio-1"> <div class="image"> <img src="[tag_companion_uri]/sections/images/image-1.png" data-size="375x220"></div> <div class="text col-padding col-xs-12"><h6 class="color4 font-400">Brending</h6> <a class="h5 font-400">Project name</a></div> </div></div> <div class="col-md-4 col-sm-6 col-xs-12"><div class="card mdc-elevation--z3 no-padding" data-hover-fx="portfolio-1"> <div class="image"> <img src="[tag_companion_uri]/sections/images/image-2.png" data-size="375x220"></div> <div class="text col-padding col-xs-12" data-type="column"><h6 class="color2 font-400">Webdesign</h6> <a class="h5 font-400">Project name</a></div> </div></div> <div class="col-md-4 col-sm-6 col-xs-12"><div class="card mdc-elevation--z3 no-padding" data-hover-fx="portfolio-1"> <div class="image"> <img src="[tag_companion_uri]/sections/images/image-3.png" data-size="375x220"></div> <div class="text col-padding col-xs-12" data-type="column"><h6 class="color5 font-400">Print</h6> <a class="h5 font-400">Project name</a></div> </div></div> <div class="col-md-4 col-sm-6 col-xs-12"><div class="card mdc-elevation--z3 no-padding" data-hover-fx="portfolio-1"> <div class="image"> <img src="[tag_companion_uri]/sections/images/image-4.png" data-size="375x220"></div> <div class="text col-padding col-xs-12" data-type="column"><h6 class="color2 font-400">Webdesign</h6> <a class="h5 font-400">Project name</a></div> </div></div> <div class="col-md-4 col-sm-6 col-xs-12"><div class="card mdc-elevation--z3 no-padding" data-hover-fx="portfolio-1"> <div class="image"> <img src="[tag_companion_uri]/sections/images/image-1.png" data-size="375x220"></div> <div class="text col-padding col-xs-12" data-type="column"><h6 class="color4 font-400">Brending</h6> <a class="h5 font-400">Project name</a></div> </div></div> <div class="col-md-4 col-sm-6 col-xs-12"><div class="card mdc-elevation--z3 no-padding" data-hover-fx="portfolio-1"> <div class="image"> <img src="[tag_companion_uri]/sections/images/image-5.png" data-size="375x220"></div> <div class="text col-padding col-xs-12" data-type="column"><h6 class="color5 font-400">Print</h6> <a class="h5 font-400">Project name</a></div> </div></div> </div></div> </div>',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-portfolio-2-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/portfolio-2-materialis.png?v=1551109271',
    'description' => 'Portfolio',
    'category' => 'portfolio',
    'prepend' => false,
    'pro' => false,
    'export' => 'module.exports={customColor:[{colorClass:{selector:".text h6",prefix:\'\',suffix:\'\'}},]}',
  ),
  33 => 
  array (
    'index' => 1139,
    'id' => 'team-1-materialis',
    'elementId' => 'team-1',
    'type' => 'section-available',
    'name' => 'Team',
    'content' => '<div data-label="Team" data-id="team-1-materialis" data-export-id="team-1-materialis" data-category="team" class="team-1m content-section content-section-spacing-large"><div class="gridContainer"> <div class="row text-center space-bottom"><div class="section-title-col" data-type="column"> <h2>Our Team</h2> <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.</p></div> </div> <div class="row spaced-cols content-center-sm" data-type="row"> <div class="col-xs-12 col-sm-6 col-md-3"> <div class="card mdc-elevation--z3 y-move no-padding no-radius"> <img class="face space-bottom-small" src="[tag_companion_uri]/sections/images/team-3.jpg"> <div data-type="column" class="col-padding-small col-padding-small-xs description-container"> <h6 class="no-margin-bottom font-700">Team Member</h6> <p class="font-300">Job Title</p> <div class="social-icons-group" data-type="group"> <a href="#"><i class="mdi mdi-facebook social-icon "></i></a> <a href="#"><i class="mdi mdi-twitter social-icon "></i></a> <a href="#"><i class="mdi mdi-instagram social-icon "></i></a> <a href="#"><i class="mdi mdi-rss social-icon "></i></a></div> </div></div> </div> <div class="col-xs-12 col-sm-6 col-md-3"> <div class="card mdc-elevation--z3 y-move no-padding no-radius"> <img class="face space-bottom-small" src="[tag_companion_uri]/sections/images/team-6.jpg"> <div data-type="column" class="col-padding-small col-padding-small-xs description-container"> <h6 class="no-margin-bottom font-700">Team Member</h6> <p class="font-300">Job Title</p> <div class="social-icons-group" data-type="group"> <a href="#"><i class="mdi mdi-facebook social-icon "></i></a> <a href="#"><i class="mdi mdi-twitter social-icon "></i></a> <a href="#"><i class="mdi mdi-instagram social-icon "></i></a> <a href="#"><i class="mdi mdi-rss social-icon "></i></a></div> </div></div> </div> <div class="col-xs-12 col-sm-6 col-md-3"> <div class="card mdc-elevation--z3 y-move no-padding no-radius"> <img class="face space-bottom-small" src="[tag_companion_uri]/sections/images/team-5.jpg"> <div data-type="column" class="col-padding-small col-padding-small-xs description-container"> <h6 class="no-margin-bottom font-700">Team Member</h6> <p class="font-300">Job Title</p> <div class="social-icons-group" data-type="group"> <a href="#"><i class="mdi mdi-facebook social-icon "></i></a> <a href="#"><i class="mdi mdi-twitter social-icon "></i></a> <a href="#"><i class="mdi mdi-instagram social-icon "></i></a> <a href="#"><i class="mdi mdi-rss social-icon "></i></a></div> </div></div> </div> <div class="col-xs-12 col-sm-6 col-md-3"> <div class="card mdc-elevation--z3 y-move no-padding no-radius"> <img class="face space-bottom-small" src="[tag_companion_uri]/sections/images/team-8.jpg"> <div data-type="column" class="col-padding-small col-padding-small-xs description-container"> <h6 class="no-margin-bottom font-700">Team Member</h6> <p class="font-300">Job Title</p> <div class="social-icons-group" data-type="group"> <a href="#"><i class="mdi mdi-facebook social-icon "></i></a> <a href="#"><i class="mdi mdi-twitter social-icon "></i></a> <a href="#"><i class="mdi mdi-instagram social-icon "></i></a> <a href="#"><i class="mdi mdi-rss social-icon "></i></a></div> </div></div> </div></div> </div></div>',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-team-1-materialis.png?v=1551109271',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/team-1-materialis.png?v=1551109271',
    'description' => 'Team',
    'category' => 'team',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
  ),
  34 => 
  array (
    'index' => 1145,
    'id' => 'team-8-materialis',
    'elementId' => 'team-7',
    'type' => 'section-available',
    'name' => 'Team',
    'content' => '<div data-label="Team" data-id="team-8-materialis" data-export-id="team-8-materialis" data-category="team" class="team-8m content-section content-section-spacing-large"><div class="gridContainer"> <div class="row space-bottom"><div class="section-title-col" data-type="column"> <h2>Our Team</h2> <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.</p></div> </div> <div class="row spaced-cols content-left-sm" data-type="row" data-max-items="4"> <div class="col-xs-12 col-sm-12 col-md-6"> <div class="row"> <div class="col-xs-12 col-sm-6 col-md-6"> <div class="card mdc-elevation--z3 no-radius image-holder" data-fixed="true"> <img class="face no-margin-bottom" src="[tag_companion_uri]/sections/images/team-4.jpg"></div> </div> <div class="col-xs-12 col-sm-6 col-md-6 right-col"> <div data-type="column" class="description-container use-section-text-color"> <h4 class="no-margin-bottom">Team Member</h4> <p class="font-300">Job Title</p> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p> <div class="social-icons-group col-no-padding" data-type="group"> <a href="#"><i class="mdi mdi-facebook social-icon "></i></a> <a href="#"><i class="mdi mdi-twitter social-icon "></i></a> <a href="#"><i class="mdi mdi-instagram social-icon "></i></a> <a href="#"><i class="mdi mdi-rss social-icon "></i></a></div> </div></div> </div></div> <div class="col-xs-12 col-sm-12 col-md-6"><div class="row"> <div class="col-xs-12 col-sm-6 col-md-6"><div class="card mdc-elevation--z3 no-radius image-holder" data-fixed="true"> <img class="face no-margin-bottom" src="[tag_companion_uri]/sections/images/team-2.jpg"></div> </div> <div class="col-xs-12 col-sm-6 col-md-6 right-col"> <div data-type="column" class="description-container use-section-text-color"> <h4 class="no-margin-bottom">Team Member</h4> <p class="font-300">Job Title</p> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p> <div class="social-icons-group col-no-padding" data-type="group"> <a href="#"><i class="mdi mdi-facebook social-icon "></i></a> <a href="#"><i class="mdi mdi-twitter social-icon "></i></a> <a href="#"><i class="mdi mdi-instagram social-icon "></i></a> <a href="#"><i class="mdi mdi-rss social-icon "></i></a></div> </div></div> </div></div> <div class="col-xs-12 col-sm-12 col-md-6"><div class="row"> <div class="col-xs-12 col-sm-6 col-md-6"><div class="card mdc-elevation--z3 no-radius image-holder" data-fixed="true"> <img class="face no-margin-bottom" src="[tag_companion_uri]/sections/images/team-6.jpg"></div> </div> <div class="col-xs-12 col-sm-6 col-md-6 right-col"> <div data-type="column" class="description-container use-section-text-color"> <h4 class="no-margin-bottom">Team Member</h4> <p class="font-300">Job Title</p> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p> <div class="social-icons-group col-no-padding" data-type="group"> <a href="#"><i class="mdi mdi-facebook social-icon "></i></a> <a href="#"><i class="mdi mdi-twitter social-icon "></i></a> <a href="#"><i class="mdi mdi-instagram social-icon "></i></a> <a href="#"><i class="mdi mdi-rss social-icon "></i></a></div> </div></div> </div></div> <div class="col-xs-12 col-sm-12 col-md-6"><div class="row"> <div class="col-xs-12 col-sm-6 col-md-6"><div class="card mdc-elevation--z3 no-radius image-holder" data-fixed="true"> <img class="face no-margin-bottom" src="[tag_companion_uri]/sections/images/team-8.jpg"></div> </div> <div class="col-xs-12 col-sm-6 col-md-6 right-col"> <div data-type="column" class="description-container use-section-text-color"> <h4 class="no-margin-bottom">Team Member</h4> <p class="font-300">Job Title</p> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p> <div class="social-icons-group col-no-padding" data-type="group"> <a href="#"><i class="mdi mdi-facebook social-icon "></i></a> <a href="#"><i class="mdi mdi-twitter social-icon "></i></a> <a href="#"><i class="mdi mdi-instagram social-icon "></i></a> <a href="#"><i class="mdi mdi-rss social-icon "></i></a></div> </div></div> </div></div> </div></div> </div>',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-team-8-materialis.png?v=1551109272',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/team-8-materialis.png?v=1551109272',
    'description' => 'Team',
    'category' => 'team',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
  ),
  35 => 
  array (
    'index' => 1148,
    'id' => 'testimonials-1-materialis',
    'elementId' => 'testimonials-2',
    'type' => 'section-available',
    'name' => 'Testimonials',
    'content' => '<div data-label="Testimonials" data-id="testimonials-1-materialis" data-export-id="testimonials-1-materialis" data-category="testimonials" class="testimonials-1m content-section content-section-spacing"><div class="gridContainer"> <div class="row space-bottom-small"><div data-type="column" class="section-title-col"> <h2>Testimonials</h2> <p class="lead">Don\'t take our word for it - here\'s what our clients say:</p></div> </div> <div class="row spaced-cols content-left-sm" data-type="row"> <div class="col-xs-12 col-sm-4 col-md-4"> <div class="card mdc-elevation--z3 small-padding no-border"> <div class="row space-bottom-small"> <div class="testimonial-body col-xs-12" data-type="column"> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud..</p></div> </div> <div class="row middle-xs f-align"> <div class="col-xs-fit col-sm-12 col-md-fit space-bottom-image" data-fixed="true"> <img data-fixed-elevation="true" class="round image-70 mdc-elevation--z3" src="[tag_companion_uri]/sections/images/team-8.jpg"></div> <div class="col-xs-fit col-sm-12 col-md-fit info no-padding-left" data-type="column"><h6 class="font-700">John Doe</h6> <p class="small font-300">Company Name</p></div> </div></div> </div> <div class="col-xs-12 col-sm-4 col-md-4"> <div class="card mdc-elevation--z3 small-padding no-border"> <div class="row space-bottom-small"> <div class="testimonial-body col-xs-12" data-type="column"> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.</p></div> </div> <div class="row middle-xs f-align"> <div class="col-xs-fit col-sm-12 col-md-fit space-bottom-image" data-fixed="true"> <img data-fixed-elevation="true" class="round image-70 mdc-elevation--z3" src="[tag_companion_uri]/sections/images/team-1.jpg"></div> <div class="col-xs-fit col-sm-12 col-md-fit info no-padding-left" data-type="column"><h6 class="font-700">Lucy Pratt</h6> <p class="small font-300">Company name</p></div> </div></div> </div> <div class="col-xs-12 col-sm-4 col-md-4"> <div class="card mdc-elevation--z3 small-padding no-border"> <div class="row space-bottom-small"> <div class="testimonial-body col-xs-12" data-type="column"> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.</p></div> </div> <div class="row middle-xs f-align"> <div class="col-xs-fit col-sm-12 col-md-fit space-bottom-image" data-fixed="true"> <img data-fixed-elevation="true" class="round image-70 mdc-elevation--z3" src="[tag_companion_uri]/sections/images/team-7.jpg"></div> <div class="col-xs-fit col-sm-12 col-md-fit info no-padding-left" data-type="column"><h6 class="font-700">John Doe</h6> <p class="small font-300">Company name</p></div> </div></div> </div></div> </div></div>',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-testimonials-1-materialis.png?v=1551109272',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/testimonials-1-materialis.png?v=1551109272',
    'description' => 'Testimonials',
    'category' => 'testimonials',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
  ),
  36 => 
  array (
    'index' => 1152,
    'id' => 'testimonials-3-materialis',
    'elementId' => 'testimonials-6',
    'type' => 'section-available',
    'name' => 'Testimonials',
    'content' => '<div data-label="Testimonials" data-id="testimonials-3-materialis" data-export-id="testimonials-3-materialis" data-category="testimonials" class="testimonials-3m content-section content-section-spacing"><div class="gridContainer"> <div class="row space-bottom-small"><div data-type="column" class="section-title-col"> <h2>Testimonials</h2> <p class="lead">Don\'t take our word for it - here\'s what our clients say:</p></div> </div> <div class="row spaced-cols content-left-sm" data-type="row"> <div class="col-xs-12 col-sm-6 col-md-3"> <div class="card mdc-elevation--z3 small-padding no-border"> <div class="row middle-xs f-align"> <div class="col-xs-fit col-sm-fit col-md-fit" data-fixed="true"> <img class="round image" src="[tag_companion_uri]/sections/images/team-8.jpg"></div> <div class="col-xs-fit col-sm-fit col-md-fit info no-padding-left" data-type="column"><h6 class="no-margin-bottom font-700">John Doe</h6> <p class="font-300">Company Name</p></div> </div> <div class="row space-bottom-small"> <div class="testimonial-body col-xs-12" data-type="column"> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></div> </div></div> </div> <div class="col-xs-12 col-sm-6 col-md-3"> <div class="card mdc-elevation--z3 small-padding no-border"> <div class="row middle-xs f-align"> <div class="col-xs-fit col-sm-fit col-md-fit" data-fixed="true"> <img class="round image" src="[tag_companion_uri]/sections/images/team-1.jpg"></div> <div class="col-xs-fit col-sm-fit col-md-fit info no-padding-left" data-type="column"><h6 class="no-margin-bottom font-700">Leila Torres</h6> <p class="font-300">Company Name</p></div> </div> <div class="row space-bottom-small"> <div class="testimonial-body col-xs-12" data-type="column"> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></div> </div></div> </div> <div class="col-xs-12 col-sm-6 col-md-3"> <div class="card mdc-elevation--z3 small-padding no-border"> <div class="row middle-xs f-align"> <div class="col-xs-fit col-sm-fit col-md-fit" data-fixed="true"> <img class="round image" src="[tag_companion_uri]/sections/images/team-6.jpg"></div> <div class="col-xs-fit col-sm-fit col-md-fit info no-padding-left" data-type="column"><h6 class="no-margin-bottom font-700">Amanda Klein</h6> <p class="font-300">Company Name</p></div> </div> <div class="row space-bottom-small"> <div class="testimonial-body col-xs-12" data-type="column"> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></div> </div></div> </div> <div class="col-xs-12 col-sm-6 col-md-3"> <div class="card mdc-elevation--z3 small-padding no-border"> <div class="row middle-xs f-align"> <div class="col-xs-fit col-sm-fit col-md-fit" data-fixed="true"> <img class="round image" src="[tag_companion_uri]/sections/images/team-7.jpg"></div> <div class="col-xs-fit col-sm-fit col-md-fit info no-padding-left" data-type="column"><h6 class="no-margin-bottom font-700">Robert Rodriquez</h6> <p class="font-300">Company Name</p></div> </div> <div class="row space-bottom-small"> <div class="testimonial-body col-xs-12" data-type="column"> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></div> </div></div> </div></div> </div></div>',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-testimonials-3-materialis.png?v=1551109272',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/testimonials-3-materialis.png?v=1551109272',
    'description' => 'Testimonials',
    'category' => 'testimonials',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
  ),
  37 => 
  array (
    'index' => 1153,
    'id' => 'testimonials-4-materialis',
    'elementId' => 'testimonials-7',
    'type' => 'section-available',
    'name' => 'Testimonials',
    'content' => '<div data-label="Testimonials" data-id="testimonials-4-materialis" data-export-id="testimonials-4-materialis" data-category="testimonials" class="testimonials-4m content-section content-section-spacing"><div class="gridContainer"> <div class="row space-bottom-small"><div data-type="column" class="section-title-col"> <h2>Testimonials</h2> <p class="lead">Don\'t take our word for it - here\'s what our clients say:</p></div> </div> <div class="row spaced-cols content-center-sm" data-type="row"> <div class="col-xs-12 col-sm-4"> <div class="card mdc-elevation--z3 box-padding-tb-medium" data-type="column"> <p class="text-center">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer ut aliquet velit, sed fringilla orci. Nam molestie ligula nunc, vestibulum blandit arcu pharetra ac.</p> <img src="[tag_companion_uri]/sections/images/team-3.jpg" class="round image-90 space-bottom-small"> <h6 class="no-margin-bottom font-700">John Doe</h6> <p class="font-300">Company Name</p></div> </div> <div class="col-xs-12 col-sm-4"> <div class="card mdc-elevation--z3 box-padding-tb-medium" data-type="column"> <p class="text-center">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer ut aliquet velit, sed fringilla orci. Nam molestie ligula nunc, vestibulum blandit arcu pharetra ac.</p> <img src="[tag_companion_uri]/sections/images/team-8.jpg" class="round image-90 space-bottom-small"> <h6 class="no-margin-bottom font-700">Minnie Cruz</h6> <p class="font-300">Company Name</p></div> </div> <div class="col-xs-12 col-sm-4"> <div class="card mdc-elevation--z3 box-padding-tb-medium" data-type="column"> <p class="text-center">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer ut aliquet velit, sed fringilla orci. Nam molestie ligula nunc, vestibulum blandit arcu pharetra ac.</p> <img src="[tag_companion_uri]/sections/images/team-2.jpg" class="round image-90 space-bottom-small"> <h6 class="no-margin-bottom font-700">Rhoda Salazar</h6> <p class="font-300">Company Name</p></div> </div></div> </div></div>',
    'thumb' => '//extendthemes.com/assets/materialis/previews/sections/thumb-testimonials-4-materialis.png?v=1551109272',
    'preview' => '//extendthemes.com/assets/materialis/previews/sections/testimonials-4-materialis.png?v=1551109272',
    'description' => 'Testimonials',
    'category' => 'testimonials',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
  ),
);
