<?php
/**
 * @package WP Simple Booking Calendar
 *
 * Copyright (c) 2010 Lennart Visscher
 */
?>

<div id="sbc-wrapper" class="wrap">
	<div id="icon-options-general" class="icon32"><br /></div>
	<h1><?php esc_html_e('WP Simple Booking Calendar', 'sbc') ?> 
	<?php if (!is_array($this->calendar) || count($this->calendar) == 0): ?>
		<a class="page-title-action" href="<?php echo $this->addControllerUrl ?>"><?php esc_html_e('Add New', 'sbc') ?></a>
	<?php endif; ?>
	</h1>
	
	<?php if (is_array($this->calendar) && count($this->calendar)): ?>
		<table class="widefat post fixed" cellspacing="0">
			<thead>
				<tr class="alt">
					<th class="manage-column column-name"><?php esc_html_e('Calendar Name', 'sbc') ?></th>
					<th class="manage-column column-created"><?php esc_html_e('Created', 'sbc') ?></th>
					<th class="manage-column column-modified"><?php esc_html_e('Modified', 'sbc') ?></th>
				</tr>
			</thead>
			<tbody>
				<tr valign="top">
					<td class="post-title column-title">
						<strong><a title="<?php esc_attr_e('Edit', 'sbc') ?> <?php echo esc_attr('‟' . $this->calendar['calendarName'] . '”') ?>" href="<?php echo $this->editControllerUrl ?>" class="row-title"><?php echo esc_html($this->calendar['calendarName']) ?></a></strong>
						<div class="row-actions">
							<span class="edit"><a title="<?php esc_attr_e('Edit this calendar', 'sbc') ?>" href="<?php echo $this->editControllerUrl ?>"><?php esc_html_e('Edit', 'sbc') ?></a> | </span>
							<span class="trash"><a title="<?php esc_attr_e('Are you sure you want to delete this calendar?', 'sbc') ?>" href="<?php echo $this->deleteControllerUrl ?>" class="submitdelete"><?php esc_html_e('Delete', 'sbc') ?></a></span>
						</div>
					</td>
					<td class="street column-created">
						<?php echo esc_html(date($this->dateFormat, $this->calendar['dateCreated'])) ?><br/>
						<?php echo esc_html(date($this->timeFormat, $this->calendar['dateCreated'])) ?>
					</td>
					<td class="street column-modified">
						<?php echo esc_html(date($this->dateFormat, $this->calendar['dateModified'])) ?><br/>
						<?php echo esc_html(date($this->timeFormat, $this->calendar['dateModified'])) ?>
					</td>
				</tr>
			</tbody>
		</table>
		<br />
		<div class="updated">
		<p style="font-size: 12px;">Paste the shortcode <strong>[sbc title="yes"]</strong> or <strong>[sbc title="no"]</strong> in a page or post to display the calendar on your website. Think you've found a bug? <a href="https://www.wpsimplebookingcalendar.com/contact/" target="_blank">Click here</a> to report it.
		</p>
	</div>
	<div class="buy-full">
		<h1>Upgrade to the Premium version</h1>
        <div class="box first">
            <h1>Free</h1>
            <ul>
                <li>Create 1 calendar</li>
            </ul>
            <span></span>
            <div class="bottom">
                <p>Your current version</p>
            </div>
            <small class="bottom">&nbsp;</small>
        </div>
        
        <div class="box second">
            <h1>Premium</h1>
            <ul>
                <li>Create unlimited calendars</li>
                <li>Display multiple months</li>
                <li>Edit multiple dates with one click</li>
                <li>Display a legend near the calendar</li>
                <li>Create your own legend</li>
                <li>Change the first day of week</li>
                <li>Change the start month &amp; year</li>
                <li>Save booking information</li>
				<li>Display tooltips with info</li>
                <li>Assign users to calendars</li>
				<li>Show the week's number</li>
				<li>Hide booking history</li>
				<li>Sync your calendars (iCalendar)</li>
				<li>Multiple calendar overview</li>
				<li>Responsive calendar themes</li>
				<li>Professional support</li>
            </ul>
            <span><small>starting at</small><h2>&dollar;39 </h2></span>
            <div class="bottom">
                <a href="http://www.wpsimplebookingcalendar.com/premium/" target="_blank" class="button">Read more</a>
            </div>
            <small class="bottom">100% money-back guarantee!</small>
        </div>

	</div>
	<?php else: ?>
		<p><?php esc_html_e('No calendars found.', 'sbc') ?> <a href="<?php echo $this->addControllerUrl ?>"><?php esc_html_e('Click here to create a new calendar.', 'sbc') ?></a></p>
	<?php endif ?>
</div>